# -*- coding: utf-8 -*-
from _catalog import CH2, CH3, CH4, L, goals, concept, choice, fill, oral, wrong

REST = [
    L(17, 94, CH2, "precyzyjna-informacja",
      ("Precyzyjna informacja", "Точна інформація"),
      "kto? gdzie? jak?",
      ("Żeby ktoś trafił", "Щоб хтось потрапив"),
      (["Podróż zaczyna się od jasnej informacji: **gdzie, którędy, o której**.",
        "Tryb rozkazujący i wyrazy kolejności (najpierw, potem, na końcu) porządkują instrukcję."],
       ["Подорож починається з ясної інформації: **де, яким шляхом, о котрій**.",
        "Наказовий спосіб і слова порядку впорядковують інструкцію."]),
      goals(("dać jasną informację przestrzenną i czasową", "дати ясну інформацію про простір і час"),
            ("użyć kolejności kroków", "ужити послідовність кроків")),
      [concept("Jasny komunikat", "Ясне повідомлення",
               ["Złe: Idź tam. Lepsze: Wyjdź bramą, skręć w lewo przy sklepie, idź 200 metrów.",
                "Cel, miejsce, kolejność, czas — jak w sytuacji komunikacyjnej z lekcji 1."],
               ["Погане: Іди туди. Краще: Вийди брамою, поверни ліворуч біля крамниці."])],
      choice(17, "Która informacja jest precyzyjna?", "Яка інформація точна?",
             [("Idź jakoś dalej", "Іди якось далі"),
              ("Skręć w prawo za pocztą i idź do światła", "Поверни праворуч за поштою і йди до світла"),
              ("Może tam, nie wiem", "Може туди, не знаю")],
             "b", "Miejsce + kierunek.", "Місце + напрям."),
      fill(17, "Jakim trybem często dajemy instrukcję? (rozkazujący)",
           "Яким способом часто даємо інструкцію? (rozkazujący)",
           ["rozkazujący", "tryb rozkazujący", "наказовий"],
           "Tryb rozkazujący.", "Наказовий спосіб."),
      wrong("„Im mniej szczegółów, tym łatwiej trafić.”",
            "«Що менше деталей, то легше потрапити.»",
            ["Bez szczegółów odbiorca zgaduje. Precyzja pomaga."],
            ["Без деталей адресат здогадується. Точність допомагає."]),
      oral(17, "Daj na głos trzy kroki drogi od klasy do wejścia szkoły.",
           "Дай уголос три кроки дороги від класу до входу школи.",
           "Co porządkuje instrukcję drogi?",
           "Що впорядковує інструкцію дороги?",
           [("kolejność kroków i konkretne punkty", "послідовність кроків і конкретні точки"),
            ("tylko rymy", "лише рими"), ("wykres zdania", "схема речення")],
           "a", "Kolejność + konkrety.", "Послідовність + конкретика."),
      [("Precyzyjna informacja podaje miejsce, kierunek, czas i kolejność.",
        ["Precyzyjna informacja", "kolejność"],
        "Точна інформація подає місце, напрям, час і послідовність.",
        ["Точна інформація", "послідовність"])]),

    L(18, 97, CH2, "liczebnik",
      ("Liczebnik", "Числівник"),
      "ile? który?",
      ("Liczba słowem", "Число словом"),
      (["**Liczebnik** mówi **ile?** albo **który z kolei?**",
        "Główne: trzy, piętnaście. Porządkowe: trzeci, piętnasty. Pisownia **nie** z liczebnikiem — zwykle osobno."],
       ["**Числівник** каже **скільки?** або **котрий за порядком?**",
        "Кількісні: trzy. Порядкові: trzeci."]),
      goals(("odróżnić liczebnik główny od porządkowego", "відрізнити кількісний числівник від порядкового"),
            ("zapis słowny prostej liczby", "словесний запис простого числа")),
      [concept("Ile i który", "Скільки і котрий",
               ["**siedem dni** — ile? **siódmy dzień** — który?",
                "W datach i kolejności używamy porządkowych."],
               ["**siedem dni** — скільки? **siódmy dzień** — котрий?"])],
      choice(18, "Który wyraz jest liczebnikiem porządkowym?", "Яке слово є порядковим числівником?",
             [("pięć", "pięć"), ("piąty", "piąty"), ("pięknie", "pięknie")],
             "b", "piąty = który?", "piąty = котрий?"),
      fill(18, "Na jakie pytanie odpowiada liczebnik główny? (ile?)",
           "На яке питання відповідає кількісний числівник? (ile?)",
           ["ile?", "ile", "скільки?"], "ile?", "скільки?"),
      wrong("„Piąty i pięć to to samo słowo, tylko ładniejsza końcówka.”",
            "«Piąty і pięć — те саме слово, лише гарніше закінчення.»",
            ["Główny: ile. Porządkowy: który z kolei."],
            ["Кількісний: скільки. Порядковий: котрий."]),
      oral(18, "Podaj liczebnik główny i porządkowy od liczby 3.",
           "Назви кількісний і порядковий числівник від числа 3.",
           "Co znaczy trzeci?",
           "Що означає trzeci?",
           [("który z kolei", "котрий за порядком"), ("kolor", "колір"), ("tryb czasownika", "спосіб дієслова")],
           "a", "Porządkowy.", "Порядковий."),
      [("Liczebnik główny odpowiada na ile?, porządkowy na który?",
        ["główny", "ile", "porządkowy", "który"],
        "Кількісний числівник — скільки?, порядковий — котрий?",
        ["Кількісний", "порядковий"])]),

    L(19, 100, CH2, "dziennik",
      ("Dziennik", "Щоденник"),
      "data · ja · dziś",
      ("Zapis dnia", "Запис дня"),
      (["**Dziennik** to zapis z datą, zwykle w pierwszej osobie, blisko wydarzeń.",
        "W podręczniku fragment Verne’a (podróż). Gatunek ≠ pamiętnik."],
       ["**Щоденник** — запис із датою, зазвичай від першої особи, близько до подій.",
        "У підручнику уривок Верна. Жанр ≠ спогади."]),
      goals(("rozpoznać cechy dziennika", "розпізнати риси щоденника"),
            ("odróżnić dziennik od pamiętnika", "відрізнити щоденник від мемуарів")),
      [concept("Dziennik a pamiętnik", "Щоденник і спогади",
               ["Dziennik: krótki dystans czasu, data, „dziś”.",
                "Pamiętnik: patrzy wstecz, często dłuższy dystans i ocena."],
               ["Щоденник: мала дистанція часу, дата, «сьогодні».",
                "Спогади / pamiętnik: погляд назад."])],
      choice(19, "Co jest typowe dla dziennika?", "Що типове для щоденника?",
             [("brak daty i opowieść o pradziadku sprzed 50 lat jako jedyna cecha",
               "відсутність дати і лише оповідь про прадіда 50 років тому"),
              ("data i zapis bliski wydarzeniom, często ja",
               "дата і запис близький до подій, часто я"),
              ("wyłącznie dymki komiksu", "виключно хмарки коміксу")],
             "b", "Data + bliskość zdarzeń.", "Дата + близькість подій."),
      fill(19, "Jak nazywamy zapis dnia z datą, zwykle w pierwszej osobie?",
           "Як називаємо запис дня з датою, зазвичай від першої особи?",
           ["dziennik", "щоденник"], "Dziennik.", "Щоденник."),
      wrong("„Dziennik i pamiętnik to zawsze identyczny gatunek.”",
            "«Щоденник і pamiętnik — завжди той самий жанр.»",
            ["Różni ich dystans czasu i sposób patrzenia."],
            ["Їх різнить дистанція часу і спосіб погляду."]),
      oral(19, "Powiedz jedną cechę dziennika.",
           "Назви одну рису щоденника.",
           "Który nagłówek pasuje do dziennika?",
           "Який заголовок пасує до щоденника?",
           [("12 maja. Dziś wyruszyliśmy o świcie.", "12 maja. Сьогодні вирушили на світанку."),
            ("Rozdział VII. Rzeczownik.", "Розділ VII. Іменник."),
            ("Przepis na ciasto.", "Рецепт тіста.")],
           "a", "Data i dziś.", "Дата і сьогодні."),
      [("Dziennik ma datę i zapis bliski wydarzeniom, zwykle w pierwszej osobie.",
        ["Dziennik", "datę", "pierwszej osobie"],
        "Щоденник має дату і запис близький до подій, зазвичай від першої особи.",
        ["Щоденник", "дату"])]),

    L(20, 109, CH2, "pamietnik",
      ("Pamiętnik", "Спогади"),
      "wspomnienie · ja",
      ("Patrzę wstecz", "Дивлюсь назад"),
      (["**Pamiętnik** to wspomnienie: autor wraca do zdarzeń i je ocenia.",
        "Pierwsza osoba, ale większy dystans niż w dzienniku."],
       ["**Pamiętnik** — спогад: автор повертається до подій і оцінює їх.",
        "Перша особа, але більша дистанція, ніж у щоденнику."]),
      goals(("wskazać cechy pamiętnika", "вказати риси спогадів"),
            ("odróżnić pamiętnik od dziennika i od opowiadania trzecioosobowego",
             "відрізнити спогади від щоденника і від оповідання від третьої особи")),
      [concept("Wspomnienie", "Спогад",
               ["Czas przeszły, „wtedy”, ocena: bałem się, cieszę się, że…",
                "To nadal **ja**, ale z innej chwili niż zapis dzienny."],
               ["Минулий час, «тоді», оцінка."])],
      choice(20, "Co odróżnia pamiętnik od dziennika?", "Що відрізняє pamiętnik від щоденника?",
             [("większy dystans czasu i ocena wspomnienia",
               "більша дистанція часу і оцінка спогаду"),
              ("brak osoby mówiącej", "відсутність особи, яка говорить"),
              ("tylko liczby pierwsze", "лише прості числа")],
             "a", "Wstecz + ocena.", "Назад + оцінка."),
      fill(20, "Jak nazywamy gatunek wspomnień pisanych zwykle w pierwszej osobie?",
           "Як називаємо жанр спогадів, писаних зазвичай від першої особи?",
           ["pamiętnik", "пам’ятник", "спогади"],
           "Pamiętnik.", "Pamiętnik (спогади)."),
      wrong("„Pamiętnik musi być pisany w trzeciej osobie jak sprawozdanie sędziego.”",
            "«Pamiętnik треба писати від третьої особи, як звіт судді.»",
            ["Typowy pamiętnik: ja wspominam."],
            ["Типовий pamiętnik: я згадую."]),
      oral(20, "Zacznij na głos jedno zdanie pamiętnika o wakacjach.",
           "Почни вголос одне речення спогаду про канікули.",
           "Które zdanie brzmi jak pamiętnik?",
           "Яке речення звучить як pamiętnik?",
           [("Wtedy po raz pierwszy zobaczyłem morze i długo nie mogłem zasnąć.",
             "Тоді вперше побачив море і довго не міг заснути."),
            ("Skręć w lewo za pocztą.", "Поверни ліворуч за поштою."),
            ("O rzeko, płyń ciszej!", "О річко, пливи тихіше!")],
           "a", "Wspomnienie + ja.", "Спогад + я."),
      [("Pamiętnik to wspomnienie z dystansu, zwykle w pierwszej osobie.",
        ["Pamiętnik", "wspomnienie"],
        "Pamiętnik — спогад з дистанції, зазвичай від першої особи.",
        ["Pamiętnik", "спогад"])]),

    L(21, 114, CH2, "czasownik",
      ("Czasownik", "Дієслово"),
      "co robi? co się dzieje?",
      ("Słowa ruchu i stanu", "Слова руху і стану"),
      (["**Czasownik** odpowiada na **co robi? co się dzieje? w jakim jest stanie?**",
        "Osoba, liczba, czas, tryb. **nie** z czasownikiem — osobno (nie biegnę), wyjątki jak niedopatrzyć sprawdzaj w słowniku."],
       ["**Дієслово** відповідає на **що робить? що діється?**",
        "**nie** з дієсловом — окремо."]),
      goals(("rozpoznać czasownik", "розпізнати дієслово"),
            ("pamiętać nie z czasownikiem osobno", "пам’ятати nie з дієсловом окремо")),
      [concept("Co robi?", "Що робить?",
               ["**czyta, spał, będziemy pisać, stań** — czasowniki.",
                "Formy: bezokolicznik **pisać**, osobowe **piszę**, rozkaźnik **pisz**."],
               ["**czyta, spał, stań** — дієслова."])],
      choice(21, "Które słowo jest czasownikiem?", "Яке слово є дієсловом?",
             [("stół", "stół"), ("biegnie", "biegnie"), ("szybki", "szybki")],
             "b", "biegnie = co robi?", "biegnie = що робить?"),
      fill(21, "Jak piszemy nie z osobową formą czasownika — razem czy osobno?",
           "Як пишемо nie з особовою формою дієслова — разом чи окремо?",
           ["osobno", "osobno.", "окремо"],
           "Osobno: nie biegnę.", "Окремо: nie biegnę."),
      wrong("„niebiegnę zawsze razem, bo tak szybciej.”",
            "«niebiegnę завжди разом, бо так швидше.»",
            ["nie z czasownikiem osobowym piszemy osobno."],
            ["nie з особовим дієсловом пишемо окремо."]),
      oral(21, "Podaj czasownik w czasie teraźniejszym, przeszłym i rozkaźniku.",
           "Назви дієслово в теперішньому, минулому і наказовому.",
           "Na jakie pytania odpowiada czasownik?",
           "На які питання відповідає дієслово?",
           [("co robi? co się dzieje?", "що робить? що діється?"),
            ("kto? co?", "хто? що?"), ("jaki?", "який?")],
           "a", "Czynność i stan.", "Дія і стан."),
      [("Czasownik nazywa czynność lub stan i odpowiada na co robi? co się dzieje?",
        ["Czasownik", "co robi"],
        "Дієслово називає дію або стан.",
        ["Дієслово"]),
       ("nie z osobową formą czasownika piszemy osobno.",
        ["nie", "osobno"],
        "nie з особовою формою дієслова пишемо окремо.",
        ["nie", "окремо"])]),

    L(22, 117, CH2, "narracja-sienkiewicz",
      ("Narracja. W pustyni i w puszczy", "Оповідь. У пустелі й пущі"),
      "kto opowiada?",
      ("Głos opowieści", "Голос оповіді"),
      (["**Narrator** opowiada. Pierwsza osoba: ja. Trzecia: on/ona/oni.",
        "Lektura: Henryk Sienkiewicz, «W pustyni i w puszczy» — czytasz w klasie, tu cecha narracji."],
       ["**Оповідач** розповідає. Перша особа: я. Третя: він/вона.",
        "Лектура: Сенкевич, «W pustyni i w puszczy»."]),
      goals(("odróżnić narrację pierwszo- i trzecioosobową", "відрізнити оповідь від першої і третьої особи"),
            ("odróżnić narratora od bohatera", "відрізнити оповідача від героя")),
      [concept("Kto mówi historię?", "Хто каже історію?",
               ["Narrator ≠ autor książki (jak podmiot ≠ poeta).",
                "Bohater działa w świecie przedstawionym. Narrator może być obok albo wewnątrz."],
               ["Оповідач ≠ автор книжки.",
                "Герой діє в зображеному світі."])],
      choice(22, "Co to narracja trzecioosobowa?", "Що таке оповідь від третьої особи?",
             [("opowieść słowami ja, mnie, mój jako jedyna forma",
               "оповідь словами я, мене як єдина форма"),
              ("opowieść o on/ona/oni, narrator na zewnątrz zdarzeń",
               "оповідь про він/вона, оповідач поза подіями"),
              ("tylko dymki komiksu", "лише хмарки коміксу")],
             "b", "On/ona — trzecia osoba.", "Він/вона — третя особа."),
      fill(22, "Jak nazywamy osobę, która opowiada w utworze epickim?",
           "Як називаємо особу, яка розповідає в епічному творі?",
           ["narrator", "оповідач"], "Narrator.", "Оповідач."),
      wrong("„Narrator to zawsze Stas Tarkowski z dowodu osobistego Sienkiewicza.”",
            "«Оповідач — завжди Стась з паспорта Сенкевича.»",
            ["Autor napisał książkę. Narrator to głos opowieści."],
            ["Автор написав книжку. Оповідач — голос оповіді."]),
      oral(22, "Powiedz zdanie w narracji pierwszoosobowej i przerób je na trzecioosobową.",
           "Скажи речення від першої особи і перероби на третю.",
           "Kto jest narratorem?",
           "Хто є оповідачем?",
           [("głos, który opowiada historię w utworze", "голос, який розповідає історію у творі"),
            ("tylko wydawca", "лише видавець"),
            ("zawsze czytelnik", "завжди читач")],
           "a", "Głos opowieści.", "Голос оповіді."),
      [("Narrator opowiada. Narracja bywa pierwszoosobowa (ja) albo trzecioosobowa (on/ona).",
        ["Narrator", "pierwszoosobowa", "trzecioosobowa"],
        "Оповідач розповідає. Оповідь буває від першої або третьої особи.",
        ["Оповідач"])]),

    L(23, 122, CH2, "herakles",
      ("Mit o Heraklesie", "Міф про Геракла"),
      "heros · prace",
      ("Siła i próba", "Сила і випробування"),
      (["**Herakles** (Herkules) to heros: syn boga i człowiek, śmiertelny, nadzwyczajnie silny.",
        "Słynne **prace** to kolejne próby. Mit uczy odwagi i konsekwencji, bez scen grozy."],
       ["**Геракл** — герой: син бога і людина, смертний, надзвичайно сильний.",
        "Славетні **праці** — випробування."]),
      goals(("powiedzieć, kim jest heros", "сказати, ким є герой (heros)"),
            ("odróżnić herosa od boga olimpijskiego", "відрізнити героя від олімпійського бога")),
      [concept("Heros", "Герой",
               ["Bóg jest nieśmiertelny. Heros ma ludzką stronę i kres życia.",
                "Prace Heraklesa to zadania ponad siły zwykłego człowieka."],
               ["Бог безсмертний. Герой має людський бік і кінець життя."])],
      choice(23, "Kim jest heros w micie greckim?", "Хто такий герой у грецькому міфі?",
             [("pełny nieśmiertelny bóg z Olimpu bez ludzkiego rodzica",
               "повний безсмертний бог з Олімпу без людського батька"),
              ("półbóg: jeden rodzic bóg, drugi człowiek; śmiertelny, niezwykły",
               "напівбог: один батько бог, другий людина; смертний, незвичайний"),
              ("liczebnik porządkowy", "порядковий числівник")],
             "b", "Heros = półbóg, śmiertelny.", "Герой = напівбог, смертний."),
      fill(23, "Jak nazywa się najsłynniejszy heros, syn Zeusa, znany z wielkich prac?",
           "Як називається найславетніший герой, син Зевса, знаний з великих праць?",
           ["Herakles", "Herkules", "herakles", "Геракл"], "Herakles.", "Геракл."),
      wrong("„Herakles to to samo co Zeus: obaj są wyłącznie bogami Olimpu bez ludzkiej strony.”",
            "«Геракл — те саме, що Зевс: обидва лише боги Олімпу.»",
            ["Zeus jest bogiem. Herakles jest herosem."],
            ["Зевс — бог. Геракл — герой."]),
      oral(23, "Powiedz, czym heros różni się od boga.",
           "Скажи, чим герой відрізняється від бога.",
           "Co jest prawdą o pracach Heraklesa?",
           "Що правда про праці Геракла?",
           [("to kolejne nadludzkie zadania-próby", "це чергові надлюдські завдання-випробування"),
            ("to odmiana przymiotnika", "це відмінювання прикметника"),
            ("to spis treści podręcznika", "це зміст підручника")],
           "a", "Próby herosa.", "Випробування героя."),
      [("Heros to półbóg, śmiertelny. Herakles słynie z nadludzkich prac.",
        ["Heros", "Herakles"],
        "Герой — напівбог, смертний. Геракл славиться надлюдськими працями.",
        ["Герой", "Геракл"])]),

    L(24, 131, CH2, "tryby-czasownika",
      ("Tryby czasownika", "Способи дієслова"),
      "oznajmujący · rozkazujący · przypuszczający",
      ("Jak mówimy o czynności", "Як говоримо про дію"),
      (["Trzy **tryby**: orzekamy, rozkazujemy, przypuszczamy.",
        "Cząstki **-bym, -byś, -by, -byśmy, -byście** piszemy z czasownikiem **łącznie** (zrobiłbym), ale **osobno** z nie (nie zrobiłbym)."],
       ["Три **способи**: стверджуємо, наказуємо, припускаємо.",
        "Частки **-bym, -byś, -by** з дієсловом **разом**."]),
      goals(("rozpoznać trzy tryby", "розпізнати три способи"),
            ("poprawnie zapisać -bym, -byś, -by", "правильно записати -bym, -byś, -by")),
      [concept("Trzy tryby", "Три способи",
               ["Oznajmujący: Idę do szkoły.",
                "Rozkazujący: Idź do szkoły.",
                "Przypuszczający: Poszedłbym, gdyby…"],
               ["Оповідний: Idę.", "Наказовий: Idź.", "Умовний: Poszedłbym."])],
      choice(24, "Które zdanie jest w trybie przypuszczającym?", "Яке речення в умовному способі?",
             [("Piszę list.", "Piszę list."), ("Napisz list.", "Napisz list."),
              ("Napisałbym list.", "Napisałbym list.")],
             "c", " -bym = przypuszczenie.", " -bym = припущення."),
      fill(24, "Napisz poprawnie: zrobił + bym (łącznie, jedno słowo)",
           "Напиши правильно: zrobił + bym (разом, одне слово)",
           ["zrobiłbym"], "zrobiłbym.", "zrobiłbym."),
      wrong("„zrobił bym zawsze osobno, bo bym to osobny wyraz jak w autobusie.”",
            "«zrobił bym завжди окремо.»",
            ["Z czasownikiem: łącznie. nie zrobiłbym — nie osobno, reszta razem."],
            ["З дієсловом: разом."]),
      oral(24, "Powiedz to samo w trzech trybach: oznajmującym, rozkazującym, przypuszczającym.",
           "Скажи те саме в трьох способах.",
           "Jak piszemy cząstkę -byś z czasownikiem?",
           "Як пишемо частку -byś з дієсловом?",
           [("łącznie: zrobiłbyś", "разом: zrobiłbyś"),
            ("zawsze w osobnym wierszu", "завжди в окремому рядку"),
            ("nigdy nie używamy", "ніколи не вживаємо")],
           "a", "łącznie z formą czasownika.", "разом із формою дієслова."),
      [("Tryby: oznajmujący, rozkazujący, przypuszczający. -bym, -byś, -by z czasownikiem łącznie.",
        ["tryby", "łącznie"],
        "Способи: оповідний, наказовий, умовний. -bym з дієсловом разом.",
        ["способи"])]),

    L(25, 134, CH2, "relacja-i-notatka",
      ("Relacja i notatka", "Реляція і нотатка"),
      "fakt · kolejność",
      ("Opowiadam, co się stało", "Розповідаю, що сталося"),
      (["**Relacja** zdaje sprawę z wydarzenia: kto, co, gdzie, kiedy.",
        "**Notatka** jest krótsza: sam szkielet informacji. W podręczniku m.in. wyprawa Marka Kamińskiego."],
       ["**Реляція** звітує про подію: хто, що, де, коли.",
        "**Нотатка** коротша: сам каркас."]),
      goals(("odróżnić relację od opowiadania z dialogiem", "відрізнити реляцію від оповідання з діалогом"),
            ("zrobić notatkę z faktów", "зробити нотатку з фактів")),
      [concept("Fakty w kolejności", "Факти в порядку",
               ["Najpierw to, co się stało, potem skutek. Bez zmyślania dialogów „dla klimatu”, jeśli to relacja.",
                "Notatka: równoważniki zdań albo krótkie punkty."],
               ["Спочатку те, що сталося, потім наслідок."])],
      choice(25, "Co jest relacją z wydarzenia?", "Що є реляцією про подію?",
             [("O wietrze, zaśpiewaj nam balladę!", "О вітре, заспівай нам баладу!"),
              ("O 8:00 start. O 14:00 dotarliśmy do schroniska. Nikt nie zginął.",
               "О 8:00 старт. О 14:00 дійшли до притулку."),
              ("Kot jest rzeczownikiem.", "Кіт — іменник.")],
             "b", "Czas, miejsce, przebieg.", "Час, місце, перебіг."),
      fill(25, "Jak nazywamy krótki zapis najważniejszych faktów?",
           "Як називаємо короткий запис найважливіших фактів?",
           ["notatka", "нотатка"], "Notatka.", "Нотатка."),
      wrong("„Relacja z wycieczki musi mieć smoki i magię, inaczej nikt nie przeczyta.”",
            "«Реляція з екскурсії мусить мати драконів, інакше ніхто не прочитає.»",
            ["Relacja trzyma się faktów. Fantazja to inne gatunki."],
            ["Реляція тримається фактів."]),
      oral(25, "Zrelacjonuj w trzech zdaniach drogę do szkoły dziś rano.",
           "Зроби реляцію в трьох реченнях про дорогу до школи сьогодні вранці.",
           "Czego relacja nie powinna robić?",
           "Чого реляція не повинна робити?",
           [("zmyślać faktów dla ozdoby", "вигадувати факти для прикраси"),
            ("podawać czas i miejsce", "подавати час і місце"),
            ("mówić, kto brał udział", "казати, хто брав участь")],
           "a", "Fakty, nie bajka.", "Факти, не казка."),
      [("Relacja podaje fakty: kto, co, gdzie, kiedy. Notatka jest jeszcze krótsza.",
        ["Relacja", "fakty", "Notatka"],
        "Реляція подає факти. Нотатка ще коротша.",
        ["Реляція", "Нотатка"])]),

    L(26, 148, CH2, "akcja-watek-fabula",
      ("Akcja, wątek, fabuła", "Дія, сюжетна лінія, фабула"),
      "zdarzenia w czasie",
      ("Co się dzieje w opowieści", "Що діється в оповіді"),
      (["**Fabuła** to układ zdarzeń. **Akcja** to przebieg zdarzeń. **Wątek** to linia jednego problemu lub bohatera.",
        "W podręczniku: tułaczka Odyseusza — wędrowanie do domu."],
       ["**Фабула** — уклад подій. **Дія** — їхній перебіг. **Сюжетна лінія (wątek)** — лінія проблеми або героя.",
        "У підручнику: мандри Одіссея."]),
      goals(("odróżnić fabułę, akcję i wątek", "відрізнити фабулу, дію і сюжетну лінію"),
            ("wskazać wątek główny", "вказати головну лінію")),
      [concept("Trzy pojęcia", "Три поняття",
               ["Fabuła = cała historia ułożona w opowieść.",
                "Wątek główny prowadzi do celu (np. powrót do domu). Wątki poboczne odchodzą na bok."],
               ["Фабула = ціла історія. Головна лінія веде до мети."])],
      choice(26, "Co to wątek główny?", "Що таке головна сюжетна лінія?",
             [("najważniejsza linia zdarzeń prowadząca do celu opowieści",
               "найважливіша лінія подій, що веде до мети оповіді"),
              ("tylko rym na końcu wersu", "лише рима в кінці рядка"),
              ("pisownia rz", "написання rz")],
             "a", "Główna linia historii.", "Головна лінія історії."),
      fill(26, "Jak nazywamy układ zdarzeń w utworze?",
           "Як називаємо уклад подій у творі?",
           ["fabuła", "fabula", "фабула"], "Fabuła.", "Фабула."),
      wrong("„Wątek poboczny to zawsze ważniejszy niż powrót Odyseusza do domu.”",
            "«Побічна лінія завжди важливіша за повернення Одіссея додому.»",
            ["Wątek główny prowadzi do celu opowieści."],
            ["Головна лінія веде до мети оповіді."]),
      oral(26, "Wskaż wątek główny znanej ci bajki lub lektury.",
           "Вкажи головну лінію відомої тобі казки або лектури.",
           "Czym jest akcja?",
           "Що таке акcja / дія?",
           [("przebieg zdarzeń w czasie", "перебіг подій у часі"),
            ("tylko okładka książki", "лише обкладинка"),
            ("liczebnik zbiorowy", "збірний числівник")],
           "a", "Zdarzenia toczą się.", "Події точаться."),
      [("Fabuła to układ zdarzeń. Akcja — ich przebieg. Wątek — linia bohatera lub problemu.",
        ["Fabuła", "Akcja", "Wątek"],
        "Фабула — уклад подій. Дія — перебіг. Сюжетна лінія — лінія героя або проблеми.",
        ["Фабула", "Дія"])]),

    L(27, 158, CH2, "czasowniki-dokonane",
      ("Czasowniki dokonane i niedokonane", "Доконані і недоконані дієслова"),
      "zrobić / robić",
      ("Czy czynność jest skończona?", "Чи дія закінчена?"),
      (["**Dokonany**: czynność skończona — napisać, zjeść.",
        "**Niedokonany**: trwanie lub powtarzanie — pisać, jeść."],
       ["**Доконаний**: дія закінчена — napisać.",
        "**Недоконаний**: тривання — pisać."]),
      goals(("odróżnić aspekt dokonany od niedokonanego", "відрізнити доконаний вид від недоконаного"),
            ("dobrać parę: pisać – napisać", "дібрати пару: pisać – napisać")),
      [concept("Pary aspektu", "Пари виду",
               ["często przedrostek: czytać → przeczytać, robić → zrobić.",
                "Nie każdy czasownik ma wygodną parę — wtedy opisujemy znaczenie."],
               ["часто префікс: czytać → przeczytać."])],
      choice(27, "Który czasownik jest dokonany?", "Яке дієслово доконане?",
             [("pisać", "pisać"), ("napisać", "napisać"), ("pisanie", "pisanie")],
             "b", "napisać = skończyć pisanie.", "napisać = закінчити писання."),
      fill(27, "Podaj bezokolicznik dokonany od czytać",
           "Подай доконаний інфінітив від czytać",
           ["przeczytać", "przeczytac"], "przeczytać.", "przeczytać."),
      wrong("„Dokonany znaczy, że czasownik jest rzeczownikiem.”",
            "«Доконаний означає, що дієслово є іменником.»",
            ["Aspekt dotyczy przebiegu czynności, nie części mowy."],
            ["Вид стосується перебігу дії, не частини мови."]),
      oral(27, "Podaj parę: niedokonany i dokonany (np. jeść – zjeść).",
           "Назви пару: недоконаний і доконаний.",
           "Co oznacza czasownik niedokonany?",
           "Що означає недоконане дієслово?",
           [("trwanie lub powtarzanie czynności", "тривання або повторення дії"),
            ("zawsze tryb rozkazujący", "завжди наказовий спосіб"),
            ("tylko wołacz", "лише кличний відмінок")],
           "a", "Trwa / powtarza się.", "Триває / повторюється."),
      [("Dokonany: czynność skończona. Niedokonany: trwanie lub powtarzanie.",
        ["Dokonany", "Niedokonany"],
        "Доконаний: дія закінчена. Недоконаний: тривання або повторення.",
        ["Доконаний", "Недоконаний"])]),

    L(28, 160, CH2, "opowiadanie-z-dialogiem",
      ("Opowiadanie z dialogiem", "Оповідання з діалогом"),
      "myślnik · mowa",
      ("Bohaterowie rozmawiają", "Герої розмовляють"),
      (["**Dialog** w opowiadaniu zapisujemy od **myślnika**. Każda zmiana osoby — nowy wiersz.",
        "Narracja toczy akcję, dialog pokazuje głosy."],
       ["**Діалог** записуємо з **тире**. Зміна особи — новий рядок."]),
      goals(("zapis dialogu od myślnika", "запис діалогу з тире"),
            ("odróżnić didaskalia od kwestii", "відрізнити ремарку від репліки")),
      [concept("Jak zapisać rozmowę", "Як записати розмову",
               ["— Gdzie idziemy? — zapytała Ola.",
                "Kwestia od myślnika. Dodatek narratora po myślniku albo w środku."],
               ["Репліка з тире. Додаток оповідача — після тире або всередині."])],
      choice(28, "Jak zaczynamy kwestię dialogu w opowiadaniu?",
             "Як починаємо репліку діалогу в оповіданні?",
             [("od myślnika", "з тире"), ("od cyfr rzymskich", "з римських цифр"),
              ("zawsze wielkim wzorem matematycznym", "завжди великою математичною формулою")],
             "a", "Myślnik na początku kwestii.", "Тире на початку репліки."),
      fill(28, "Jakim znakiem zaczynamy kwestię dialogu? (myślnik)",
           "Яким знаком починаємо репліку діалогу? (myślnik)",
           ["myślnik", "myslnik", "—", "-", "тире"], "Myślnik.", "Тире."),
      wrong("„Dialog w opowiadaniu piszemy w dymkach jak w komiksie, bez myślników.”",
            "«Діалог в оповіданні пишемо в хмарках як у коміксі, без тире.»",
            ["W opowiadaniu: myślnik i nowy wiersz. Komiks ma dymki."],
            ["В оповіданні: тире. Комікс має хмарки."]),
      oral(28, "Powiedz dwie krótkie kwestie dialogu ucznia i nauczyciela.",
           "Скажи дві короткі репліки учня і вчителя.",
           "Kiedy w dialogu zaczynamy nowy wiersz?",
           "Коли в діалозі починаємо новий рядок?",
           [("gdy zmienia się osoba mówiąca", "коли змінюється особа, яка говорить"),
            ("po każdej spójce i", "після кожного сполучника i"),
            ("nigdy", "ніколи")],
           "a", "Nowa osoba = nowy wiersz.", "Нова особа = новий рядок."),
      [("Dialog w opowiadaniu zapisujemy od myślnika; nowa osoba — nowy wiersz.",
        ["Dialog", "myślnika"],
        "Діалог в оповіданні записуємо з тире; нова особа — новий рядок.",
        ["Діалог", "тире"])]),

    L(29, 167, CH2, "przyslowek-i-zaimek",
      ("Przysłówek i zaimek", "Прислівник і займенник"),
      "jak? gdzie? · kto/ten",
      ("Określamy czynność i zastępujemy nazwę", "Означаємо дію і замінюємо назву"),
      (["**Przysłówek**: jak? gdzie? kiedy? — szybko, tu, wczoraj. Często nieodmienny.",
        "**Zaimek** zastępuje rzeczownik lub inną część mowy: ja, ten, jakiś, który."],
       ["**Прислівник**: як? де? коли?",
        "**Займенник** замінює іменник або іншу частину мови."]),
      goals(("rozpoznać przysłówek i zaimek", "розпізнати прислівник і займенник"),
            ("nie mylić przymiotnika z przysłówkiem", "не плутати прикметник з прислівником")),
      [concept("Jak? vs jaki?", "Як? проти який?",
               ["**szybki bieg** — przymiotnik (jaki bieg?). **biegnie szybko** — przysłówek (jak biegnie?).",
                "Zaimek: **Ona** (kto?) weszła. **Ten** dom (który?)."],
               ["**szybki bieg** — прикметник. **biegnie szybko** — прислівник."])],
      choice(29, "Które słowo jest przysłówkiem?", "Яке слово є прислівником?",
             [("szybki", "szybki"), ("szybko", "szybko"), ("szybkość", "szybkość")],
             "b", "szybko = jak?", "szybko = як?"),
      fill(29, "Jak nazywamy część mowy, która zastępuje rzeczownik (np. on, ten)?",
           "Як називаємо частину мови, що замінює іменник (on, ten)?",
           ["zaimek", "займенник"], "Zaimek.", "Займенник."),
      wrong("„szybko i szybki to zawsze ta sama część mowy.”",
            "«szybko і szybki — завжди та сама частина мови.»",
            ["szybki określa rzeczownik, szybko — czasownik."],
            ["szybki означає іменник, szybko — дієслово."]),
      oral(29, "Podaj jeden przysłówek i jeden zaimek w zdaniu.",
           "Назви один прислівник і один займенник у реченні.",
           "Co robi zaimek?",
           "Що робить займенник?",
           [("zastępuje inną część mowy, często rzeczownik",
             "замінює іншу частину мови, часто іменник"),
            ("zawsze stopniuje się jak przymiotnik w tym samym słowie",
             "завжди ступенюється як прикметник у тому самому слові"),
            ("to to samo co mit", "це те саме, що міф")],
           "a", "Zastępuje nazwę.", "Замінює назву."),
      [("Przysłówek: jak? gdzie? kiedy? Zaimek zastępuje rzeczownik lub inną część mowy.",
        ["Przysłówek", "Zaimek"],
        "Прислівник: як? де? коли? Займенник замінює іменник або іншу частину мови.",
        ["Прислівник", "Займенник"])]),

    L(30, 181, CH2, "list-oficjalny-i-przyimek",
      ("List oficjalny i przyimek", "Офіційний лист і прийменник"),
      "Szanowny · przy + rzeczownik",
      ("Oficjalnie i z przyimkiem", "Офіційно і з прийменником"),
      (["List **oficjalny**: Szanowny Panie / Szanowna Pani, rzeczowy ton, zwroty grzecznościowe, podpis.",
        "**Przyimek** jest nieodmienny: do, od, na, pod, przy. Łączy się z przypadkiem rzeczownika. Pisownia przyimków złożonych: **ponad, popod** — sprawdzaj."],
       ["Офіційний лист: ввічливий тон, підпис.",
        "**Прийменник** невідмінюваний: do, na, przy."]),
      goals(("odróżnić list oficjalny od prywatnego", "відрізнити офіційний лист від приватного"),
            ("rozpoznać przyimek i wyrażenie przyimkowe", "розпізнати прийменник і прийменниковий вислів")),
      [concept("Oficjalny ton", "Офіційний тон",
               ["Nie: Siema, szefie. Tak: Szanowny Panie Dyrektorze, zwracam się z prośbą…",
                "**do szkoły, na stole, przy oknie** — wyrażenia przyimkowe."],
               ["Не: Siema. Так: Szanowny Panie…",
                "**do szkoły, na stole** — прийменникові вислови."])],
      choice(30, "Które zdanie pasuje do listu oficjalnego?", "Яке речення пасує до офіційного листа?",
             [("Siema, daj wolne.", "Siema, дай вихідний."),
              ("Szanowny Panie, zwracam się z prośbą o usprawiedliwienie nieobecności.",
               "Szanowny Panie, звертаюся з проханням…"),
              ("O księżycu, zaświeć!", "О місяцю, засвіти!")],
             "b", "Zwrot grzecznościowy + prośba.", "Ввічливе звертання + прохання."),
      fill(30, "Jak nazywamy nieodmienną część mowy w wyrażeniu do szkoły?",
           "Як називаємо невідмінювану частину мови у вислові do szkoły?",
           ["przyimek", "прийменник"], "Przyimek.", "Прийменник."),
      wrong("„Przyimek odmieniamy przez przypadki jak kot: przyimka, przyimkowi.”",
            "«Прийменник відмінюємо як кіт.»",
            ["Przyimek jest nieodmienny. Odmienia się rzeczownik obok."],
            ["Прийменник невідмінюваний. Відмінюється іменник поруч."]),
      oral(30, "Zacznij na głos list oficjalny do wychowawcy.",
           "Почни вголос офіційний лист до класного керівника.",
           "Co to wyrażenie przyimkowe?",
           "Що таке прийменниковий вислів?",
           [("przyimek + rzeczownik (często z określeniem): na stole",
             "прийменник + іменник: na stole"),
            ("tylko wykrzyknik", "лише вигук"),
            ("mit o Demeter", "міф про Деметру")],
           "a", "do szkoły, na stole.", "do szkoły, na stole."),
      [("List oficjalny ma grzeczny zwrot i rzeczowy ton. Przyimek jest nieodmienny.",
        ["oficjalny", "Przyimek"],
        "Офіційний лист має ввічливе звертання. Прийменник невідмінюваний.",
        ["офіційний", "Прийменник"])]),

    L(31, 194, CH3, "swiat-ludzkich-spraw",
      ("Świat ludzkich spraw", "Світ людських справ"),
      "uczucia · zachowanie",
      ("Jak się zachować", "Як поводитися"),
      (["Dział o ludziach: emocje, spory, przyjaźń, wybory.",
        "Znowu sytuacja komunikacyjna — teraz bliżej uczuć i zasad."],
       ["Розділ про людей: емоції, суперечки, дружба, вибір."]),
      goals(("nazwać uczucie z sytuacji", "назвати почуття з ситуації"),
            ("dopasować zachowanie do sytuacji", "дібрати поведінку до ситуації")),
      [concept("Emocja i forma", "Емоція і форма",
               ["Złość nie musi znaczyć krzyku. Można powiedzieć: jestem zły, bo… i podać powód.",
                "Gest i mimika z lekcji 1 wracają: czasem mówią więcej niż zdanie."],
               ["Злість не мусить означати крик. Можна сказати: злюся, бо…"])],
      choice(31, "Co pomaga w trudnej rozmowie?", "Що допомагає в важкій розмові?",
             [("nazwać uczucie i powód, słuchać drugiej strony",
               "назвати почуття і причину, слухати іншу сторону"),
              ("tylko krzyczeć głośniej", "лише кричати голосніше"),
              ("udawać, że nic nie czujemy, zawsze", "завжди вдавати, що нічого не відчуваємо")],
             "a", "Uczucie + powód + słuchanie.", "Почуття + причина + слухання."),
      fill(31, "Jak nazywamy przekaz bez słów: gest, mimika, postawa? (niewerbalna / komunikacja niewerbalna)",
           "Як називаємо передачу без слів: жест, міміка? (niewerbalna)",
           ["niewerbalna", "komunikacja niewerbalna", "невербальна"],
           "Komunikacja niewerbalna.", "Невербальна комунікація."),
      wrong("„W sporze wygrywa ten, kto nie słucha.”",
            "«У суперечці виграє той, хто не слухає.»",
            ["Słuchanie jest częścią rozmowy, nie słabością."],
            ["Слухання є частиною розмови."]),
      oral(31, "Nazwij uczucie i powiedz, jak można je wyrazić spokojnie.",
           "Назви почуття і скажи, як висловити його спокійно.",
           "Co należy powiedzieć oprócz nazwy uczucia?",
           "Що варто сказати крім назви почуття?",
           [("powód: jestem zły, bo…", "причину: злюся, бо…"),
            ("tylko liczbę π", "лише число π"),
            ("nic, wystarczy drzwi trzasnąć", "нічого, досить грюкнути дверима")],
           "a", "Uczucie + bo.", "Почуття + бо."),
      [("W świecie ludzkich spraw nazywamy uczucia i dobieramy zachowanie do sytuacji.",
        ["uczucia", "zachowanie"],
        "У світі людських справ називаємо почуття і добираємо поведінку до ситуації.",
        ["почуття", "поведінку"])]),

    L(32, 196, CH3, "fabula-utworu",
      ("Zdarzenie, wątek, akcja, fabuła", "Подія, лінія, дія, фабула"),
      "porządek historii",
      ("Składamy historię", "Складаємо історію"),
      (["Powtórka pojęć z lekcji 26, bliżej lektur o ludziach.",
        "Zdarzenie to jeden fakt. Fabuła układa fakty w opowieść."],
       ["Повтор понять з уроку 26, ближче до лектур про людей."]),
      goals(("odróżnić zdarzenie od fabuły", "відрізнити подію від фабули"),
            ("ułożyć trzy zdarzenia w kolejności", "скласти три події в порядку")),
      [concept("Od faktu do opowieści", "Від факту до оповіді",
               ["Zdarzenie: piłka wpadła do rzeki.",
                "Fabuła: kto grał, jak wpadła, co zrobili, czym się skończyło."],
               ["Подія: м’яч упав у річку. Фабула: хто, як, що далі."])],
      choice(32, "Co jest pojedynczym zdarzeniem?", "Що є окремою подією?",
             [("cała lektura od pierwszej do ostatniej strony", "уся лектура від першої до останньої сторінки"),
              ("jeden fakt w czasie: piłka wpadła do wody", "один факт у часі: м’яч упав у воду"),
              ("spis przypadków rzeczownika", "список відмінків іменника")],
             "b", "Zdarzenie = jeden fakt.", "Подія = один факт."),
      fill(32, "Jak nazywamy jeden fakt w czasie w utworze?",
           "Як називаємо один факт у часі у творі?",
           ["zdarzenie", "подія"], "Zdarzenie.", "Подія."),
      wrong("„Fabuła to zawsze jedno zdanie bez początku i końca.”",
            "«Фабула — завжди одне речення без початку і кінця.»",
            ["Fabuła układa wiele zdarzeń w całość."],
            ["Фабула складає багато подій у цілість."]),
      oral(32, "Podaj trzy zdarzenia z dowolnej znanej historii w kolejności.",
           "Назви три події з відомої історії по порядку.",
           "Co robi fabuła ze zdarzeniami?",
           "Що робить фабула з подіями?",
           [("układa je w opowieść", "складає їх в оповідь"),
            ("usuwa wszystkie czasowniki", "вилучає всі дієслова"),
            ("zamienia je w liczebniki", "замінює їх на числівники")],
           "a", "Układ zdarzeń.", "Уклад подій."),
      [("Zdarzenie to jeden fakt. Fabuła układa zdarzenia w opowieść.",
        ["Zdarzenie", "Fabuła"],
        "Подія — один факт. Фабула складає події в оповідь.",
        ["Подія", "Фабула"])]),

    L(33, 207, CH3, "wypowiedzenia",
      ("Wypowiedzenia. Zdanie i równoważnik", "Висловлювання. Речення і еквівалент"),
      "orzeczenie?",
      ("Czy jest orzeczenie?", "Чи є присудок?"),
      (["**Zdanie** ma **orzeczenie** (zwykle czasownik). **Równoważnik zdania** nie ma orzeczenia: Noc. Cisza.",
        "Pytające, oznajmujące, rozkazujące, wykrzyknikowe — cel wypowiedzi."],
       ["**Речення** має **присудок**. **Еквівалент речення** не має присудка: Noc."]),
      goals(("odróżnić zdanie od równoważnika", "відрізнити речення від еквівалента"),
            ("rozpoznać zdanie pytające i rozkazujące", "розпізнати питальне і наказове речення")),
      [concept("Orzeczenie rozstrzyga", "Присудок вирішує",
               ["Deszcz pada. — zdanie.",
                "Ulewa. — równoważnik.",
                "Pytajnik, kropka, wykrzyknik pomagają odczytać cel."],
               ["Deszcz pada. — речення. Ulewa. — еквівалент."])],
      choice(33, "Które to równoważnik zdania?", "Що є еквівалентом речення?",
             [("Idziemy do domu.", "Idziemy do domu."),
              ("Czas do domu.", "Czas do domu."),
              ("Czy idziemy do domu?", "Czy idziemy do domu?")],
             "b", "Brak orzeczenia.", "Немає присудка."),
      fill(33, "Jak nazywamy wypowiedzenie z orzeczeniem?",
           "Як називаємо висловлювання з присудком?",
           ["zdanie", "речення"], "Zdanie.", "Речення."),
      wrong("„Każdy napis na plakacie to zdanie, nawet samo STOP.”",
            "«Кожен напис на плакаті — речення, навіть саме STOP.»",
            ["STOP bywa równoważnikiem. Zdanie ma orzeczenie."],
            ["STOP буває еквівалентом. Речення має присудок."]),
      oral(33, "Podaj zdanie i równoważnik o pogodzie.",
           "Назви речення і еквівалент про погоду.",
           "Po czym poznasz zdanie?",
           "По чому впізнаєш речення?",
           [("ma orzeczenie", "має присудок"),
            ("zawsze rymuje się", "завжди римується"),
            ("musi mieć apostrofę", "мусить мати апострофу")],
           "a", "Orzeczenie.", "Присудок."),
      [("Zdanie ma orzeczenie. Równoważnik zdania orzeczenia nie ma.",
        ["Zdanie", "orzeczenie", "Równoważnik"],
        "Речення має присудок. Еквівалент речення присудка не має.",
        ["Речення", "присудок"])]),

    L(34, 212, CH3, "chlopcy-z-placu-broni",
      ("Chłopcy z Placu Broni", "Хлопці з Площі Зброї"),
      "przyjaźń · honor · konflikt",
      ("Plac, który się broni", "Площа, яка захищається"),
      (["Lektura obowiązkowa: Ferenc Molnár, «Chłopcy z Placu Broni».",
        "Tu: świat przedstawiony, konflikt o miejsce, przyjaźń i zasady grupy — bez streszczenia całej książki."],
       ["Обов’язкова лектура: Ференц Мольнар.",
        "Тут: зображений світ, конфлікт, дружба і правила групи."]),
      goals(("wskazać temat konfliktu (miejsce / honor grupy)", "вказати тему конфлікту"),
            ("odróżnić bohatera głównego od tła", "відрізнити головного героя від тла")),
      [concept("O co toczy się spór?", "Про що суперечка?",
               ["Chłopcy bronią **swojego miejsca**. Konflikt pokazuje lojalność, odwagę i cenę zasady.",
                "Na lekcji łączysz fabułę z pojęciami: wątek, narrator, dialog."],
               ["Хлопці захищають **своє місце**. Конфлікт показує вірність і ціну правила."])],
      choice(34, "O co toczy się ważny konflikt w tej lekturze?",
             "Про що важливий конфлікт у цій лектурі?",
             [("o obronę miejsca i zasady grupy", "про захист місця і правила групи"),
              ("o pisownię ó", "про написання ó"),
              ("o pole trapezu", "про площу трапеції")],
             "a", "Plac i honor grupy.", "Площа і честь групи."),
      fill(34, "Podaj nazwisko autora «Chłopców z Placu Broni»",
           "Подай прізвище автора «Хлопців з Площі Зброї»",
           ["Molnár", "Molnar", "Ferenc Molnár", "Мольнар"],
           "Molnár.", "Мольнар."),
      wrong("„To książka wyłącznie o treningu piłki nożnej bez żadnego sporu.”",
            "«Це книжка лише про футбольне тренування без жодної суперечки.»",
            ["Konflikt o plac i zasady jest osią opowieści."],
            ["Конфлікт про площу і правила — вісь оповіді."]),
      oral(34, "Powiedz, czym dla bohaterów jest ich plac.",
           "Скажи, чим для героїв є їхня площа.",
           "Czego uczy konflikt w tej lekturze (na poziomie klasy 5)?",
           "Чого вчить конфлікт у цій лектурі?",
           [("że miejsce i obietnica wobec grupy mają wagę",
             "що місце і обіцянка групі мають вагу"),
            ("że nie trzeba mieć przyjaciół", "що не треба мати друзів"),
            ("że mit i zdanie to to samo", "що міф і речення — те саме")],
           "a", "Miejsce + lojalność.", "Місце + вірність."),
      [("«Chłopcy z Placu Broni» to lektura o przyjaźni, honorze grupy i konflikcie o miejsce.",
        ["przyjaźni", "honorze", "konflikcie"],
        "«Хлопці з Площі Зброї» — лектура про дружбу, честь групи і конфлікт за місце.",
        ["дружку", "честь", "конфлікт"])]),

    L(35, 218, CH3, "bajka",
      ("Bajka", "Байка"),
      "morał · zwierzęta",
      ("Ucząca historia", "Повчальна історія"),
      (["**Bajka** (gatunek) często ma zwierzęta-ludzi i **morał**.",
        "Krótka, pouczająca, podobna duchem do przypowieści, ale zwykle z wyraźną puentą o wadzie."],
       ["**Байка** часто має тварин-людей і **мораль**."]),
      goals(("rozpoznać bajkę jako gatunek", "розпізнати байку як жанр"),
            ("wskazać morał", "вказати мораль")),
      [concept("Zwierzę mówi o nas", "Тварина каже про нас",
               ["Lis bywa przebiegły, osioł uparty — to maski wad i zalet ludzi.",
                "Morał bywa na końcu albo wynika z puenty."],
               ["Лис буває хитрий — маска людської риси. Мораль — наприкінці або з пуанти."])],
      choice(35, "Co jest cechą bajki?", "Що є рисою байки?",
             [("brak jakiegokolwiek pouczenia", "відсутність будь-якого повчання"),
              ("krótka historia, często zwierzęta, morał",
               "коротка історія, часто тварини, мораль"),
              ("tylko wykres zdania", "лише схема речення")],
             "b", "Historia + morał.", "Історія + мораль."),
      fill(35, "Jak nazywamy pouczenie w bajce?",
           "Як називаємо повчання в байці?",
           ["morał", "мораль"], "Morał.", "Мораль."),
      wrong("„Bajka to to samo co dziennik z datą i dzisiejszą pogodą.”",
            "«Байка — те саме, що щоденник з датою і сьогоднішньою погодою.»",
            ["Bajka jest gatunkiem pouczającym, dziennik — zapisem dnia."],
            ["Байка — повчальний жанр, щоденник — запис дня."]),
      oral(35, "Wymień jedną bajkę, którą znasz, i jej morał jednym zdaniem.",
           "Назви одну байку, яку знаєш, і її мораль одним реченням.",
           "Po co w bajce zwierzęta?",
           "Навіщо в байці тварини?",
           [("pokazują wady i zalety ludzi", "показують вади і чесноти людей"),
            ("zastępują liczebnik", "замінюють числівник"),
            ("służą tylko do dyktanda z ch", "служать лише для диктанту з ch")],
           "a", "Maski ludzkich cech.", "Маски людських рис."),
      [("Bajka to krótka pouczająca opowieść, często ze zwierzętami i morałem.",
        ["Bajka", "morałem"],
        "Байка — коротка повчальна оповідь, часто з тваринами і мораллю.",
        ["Байка", "мораллю"])]),

    L(36, 227, CH3, "zdanie-pojedyncze",
      ("Zdanie pojedyncze", "Просте речення"),
      "jedno orzeczenie",
      ("Jedna myśl, jedno orzeczenie", "Одна думка, один присудок"),
      (["**Zdanie pojedyncze** ma jedno orzeczenie. Może być **nierozwinięte** (Ptak śpiewa.) albo **rozwinięte** (Mały ptak śpiewa na gałęzi.).",
        "Rozwinięcie to przydawki, dopełnienia, okoliczniki — wrócą w lekcji o częściach zdania."],
       ["**Просте речення** має один присудок. Може бути нерозвиненим або розвиненим."]),
      goals(("rozpoznać zdanie pojedyncze", "розпізнати просте речення"),
            ("odróżnić rozwinięte od nierozwiniętego", "відрізнити розвинене від нерозвиненого")),
      [concept("Rozwijać zdanie", "Розвивати речення",
               ["Nierozwinięte: podmiot + orzeczenie.",
                "Rozwinięte: dochodzą określenia."],
               ["Нерозвинене: підмет + присудок. Розвинене: з’являються означення."])],
      choice(36, "Które zdanie jest pojedyncze nierozwinięte?", "Яке речення просте нерозвинене?",
             [("Siostra czyta.", "Siostra czyta."),
              ("Moja młodsza siostra czyta cicho w kuchni.",
               "Moja młodsza siostra czyta cicho w kuchni."),
              ("Siostra czyta i brat pisze.", "Siostra czyta i brat pisze.")],
             "a", "Jedno orzeczenie, bez określeń.", "Один присудок, без означень."),
      fill(36, "Ile orzeczeń ma zdanie pojedyncze? (cyfra)",
           "Скільки присудків має просте речення? (цифра)",
           ["1", "jedno", "один"], "Jedno.", "Один."),
      wrong("„Zdanie pojedyncze musi mieć trzy orzeczenia, inaczej jest niepełne.”",
            "«Просте речення мусить мати три присудки.»",
            ["Pojedyncze = jedno orzeczenie."],
            ["Просте = один присудок."]),
      oral(36, "Rozwiń zdanie: Pies szczeka.",
           "Розвинь речення: Pies szczeka.",
           "Co dodajemy, rozwijając zdanie?",
           "Що додаємо, розвиваючи речення?",
           [("określenia: jaki pies, jak szczeka, gdzie",
             "означення: який пес, як гавкає, де"),
            ("drugie orzeczenie z innego zdania zawsze",
             "другий присудок з іншого речення завжди"),
            ("tylko apostrofę", "лише апострофу")],
           "a", "Określenia.", "Означення."),
      [("Zdanie pojedyncze ma jedno orzeczenie. Rozwinięte zawiera określenia.",
        ["pojedyncze", "jedno orzeczenie"],
        "Просте речення має один присудок. Розвинене містить означення.",
        ["просте", "один присудок"])]),

    L(37, 238, CH3, "zwiazki-wyrazowe",
      ("Związki wyrazowe", "Словосполучення"),
      "nadrzędny · podrzędny",
      ("Wyrazy się trzymają", "Слова тримаються вкупі"),
      (["W związku jest wyraz **nadrzędny** i **podrzędny** (określający).",
        "Związek zgody: ładny dom. Związek rządu: czytam książkę. Związek przynależności: idę szybko."],
       ["У зв’язку є слово **головне** і **залежне**.",
        "Узгодження, керування, прилягання."]),
      goals(("wskazać nadrzędny i podrzędny", "вказати головне і залежне"),
            ("odróżnić zgodę, rząd i przynależność na przykładach",
             "відрізнити узгодження, керування і прилягання")),
      [concept("Trzy związki", "Три зв’язки",
               ["**Zgoda**: przymiotnik dopasowuje się do rzeczownika.",
                "**Rząd**: czasownik wymaga przypadku (czytam kogo? co? książkę).",
                "**Przynależność**: przysłówek nie odmienia się, „przylepia się” do czasownika."],
               ["**Узгодження**, **керування**, **прилягання**."])],
      choice(37, "Jaki związek jest w ładny dom?", "Який зв’язок у ładny dom?",
             [("zgody", "узгодження"), ("tylko apostrofy", "лише апострофи"),
              ("żaden, to dwa mity", "жоден, це два міфи")],
             "a", "Przymiotnik zgadza się z rzeczownikiem.", "Прикметник узгоджується з іменником."),
      fill(37, "Jak nazywamy wyraz, który jest określany w związku? (nadrzędny)",
           "Як називаємо слово, яке означають у зв’язку? (nadrzędny)",
           ["nadrzędny", "wyraz nadrzędny", "головне"],
           "Nadrzędny.", "Головне (nadrzędny)."),
      wrong("„W związku wyrazowym oba wyrazy są zawsze nadrzędne.”",
            "«У словосполученні обидва слова завжди головні.»",
            ["Jeden nadrzędny, drugi podrzędny."],
            ["Одне головне, друге залежне."]),
      oral(37, "Podaj przykład związku zgody i związku rządu.",
           "Наведи приклад узгодження і керування.",
           "Co to związek rządu?",
           "Що таке керування?",
           [("nadrzędny wymaga określonej formy podrzędnego, np. czytam książkę",
             "головне вимагає певної форми залежного, напр. czytam książkę"),
            ("zawsze dwa wykrzykniki", "завжди два вигуки"),
            ("mit o Korze", "міф про Кору")],
           "a", "Rząd = wymagany przypadek.", "Керування = потрібний відмінок."),
      [("W związku jest wyraz nadrzędny i podrzędny. Zgoda, rząd, przynależność.",
        ["nadrzędny", "podrzędny"],
        "У зв’язку є головне і залежне слово. Узгодження, керування, прилягання.",
        ["головне", "залежне"])]),

    L(38, 241, CH3, "pan-tadeusz",
      ("Pan Tadeusz (fragment)", "Пан Тадеуш (уривок)"),
      "epopeja · obraz",
      ("Kraj lat dziecinnych", "Край дитячих літ"),
      (["Adam Mickiewicz, «Pan Tadeusz» — epopeja. W klasie 5 czytasz **fragment**, nie całość.",
        "Zwracasz uwagę na obrazy (opis przyrody, dwór) i na to, że to opowieść wierszem."],
       ["Міцкевич, «Пан Тадеуш» — епопея. У 5 класі — **уривок**.",
        "Звертаєш увагу на образи і на те, що це оповідь віршем."]),
      goals(("powiedzieć, kim jest autor i jaki to gatunek (epopeja)",
             "сказати, хто автор і який це жанр (епопея)"),
            ("wskazać, że fragment buduje obrazy", "вказати, що уривок будує образи")),
      [concept("Epopeja i obraz", "Епопея і образ",
               ["Epopeja opowiada o wspólnej przeszłości narodu wielkim wierszem.",
                "Nie cytujemy tu inwokacji — czytasz ją w książce. Pamiętasz: apostrofa już była na lekcji 2."],
               ["Епопея розповідає про спільне минуле великим віршем."])],
      choice(38, "Kim jest autor «Pana Tadeusza»?", "Хто автор «Пана Тадеуша»?",
             [("Adam Mickiewicz", "Адам Міцкевич"),
              ("Henryk Sienkiewicz", "Генрик Сенкевич"),
              ("Ferenc Molnár", "Ференц Мольнар")],
             "a", "Mickiewicz.", "Міцкевич."),
      fill(38, "Jak nazywamy wielki utwór wierszem o dziejach wspólnoty? (epopeja)",
           "Як називаємо великий твір віршем про долю спільноти? (epopeja)",
           ["epopeja", "епопея"], "Epopeja.", "Епопея."),
      wrong("„«Pan Tadeusz» to komiks o Asteriksie.”",
            "««Пан Тадеуш» — комікс про Астерікса.»",
            ["To epopeja Mickiewicza."],
            ["Це епопея Міцкевича."]),
      oral(38, "Powiedz, czym epopeja różni się od krótkiej bajki.",
           "Скажи, чим епопея відрізняється від короткої байки.",
           "Co czytasz z «Pana Tadeusza» w klasie 5?",
           "Що читаєш з «Пана Тадеуша» в 5 класі?",
           [("wybrany fragment, niekoniecznie całą księgę",
             "вибраний уривок, не обов’язково всю поему"),
            ("tylko spis treści matematyki", "лише зміст математики"),
            ("instrukcję pralki", "інструкцію до пралки")],
           "a", "Fragment w klasie 5.", "Уривок у 5 класі."),
      [("«Pan Tadeusz» Adama Mickiewicza to epopeja. W klasie 5 czytamy fragment i jego obrazy.",
        ["Mickiewicza", "epopeja", "fragment"],
        "«Пан Тадеуш» Адама Міцкевича — епопея. У 5 класі читаємо уривок і його образи.",
        ["Міцкевича", "епопея"])]),

    L(39, 244, CH3, "instrukcja",
      ("Instrukcja", "Інструкція"),
      "kroki · rozkaźnik",
      ("Kolejność działań", "Послідовність дій"),
      (["**Instrukcja** mówi, **jak coś zrobić**: numerowane kroki, tryb rozkazujący lub bezokolicznik.",
        "Jasność > ozdoby. To kuzyn precyzyjnej informacji z lekcji 17."],
       ["**Інструкція** каже, **як щось зробити**: кроки, наказ або інфінітив."]),
      goals(("ułożyć krótką instrukcję", "скласти коротку інструкцію"),
            ("odróżnić instrukcję od opowiadania", "відрізнити інструкцію від оповідання")),
      [concept("Krok po kroku", "Крок за кроком",
               ["1. Weź zeszyt. 2. Otwórz na czystej stronie. 3. Zapisz datę.",
                "Czasem: Otworzyć zeszyt. (bezokolicznik)"],
               ["Нумеровані кроки. Іноді інфінітив."])],
      choice(39, "Co jest instrukcją?", "Що є інструкцією?",
             [("O księżycu, płyń po niebie!", "О місяцю, пливи небом!"),
              ("1. Umyj ręce. 2. Otwórz kran. 3. Zakręć kran.",
               "1. Вмий руки. 2. Відкрий кран. 3. Закрий кран."),
              ("Wtedy pierwszy raz zobaczyłem morze…", "Тоді вперше побачив море…")],
             "b", "Kroki + rozkaźnik.", "Кроки + наказ."),
      fill(39, "Jak nazywamy tekst, który po kolei mówi, jak coś wykonać?",
           "Як називаємо текст, який по черзі каже, як щось виконати?",
           ["instrukcja", "інструкція"], "Instrukcja.", "Інструкція."),
      wrong("„Instrukcja musi mieć morał jak bajka.”",
            "«Інструкція мусить мати мораль, як байка.»",
            ["Instrukcja ma kroki, nie pouczenie o lisie."],
            ["Інструкція має кроки, не повчання про лиса."]),
      oral(39, "Podaj trzy kroki instrukcji: jak otworzyć podręcznik na stronie 10.",
           "Дай три кроки інструкції: як відкрити підручник на сторінці 10.",
           "Jaki tryb często jest w instrukcji?",
           "Який спосіб часто є в інструкції?",
           [("rozkazujący albo bezokolicznik", "наказовий або інфінітив"),
            ("tylko przypuszczający z -bym", "лише умовний з -bym"),
            ("wołacz rzeczownika jako jedyna forma", "кличний іменника як єдина форма")],
           "a", "Zrób / zrobić.", "Зроби / зробити."),
      [("Instrukcja to kolejne kroki wykonania czynności, zwykle w trybie rozkazującym.",
        ["Instrukcja", "kroki"],
        "Інструкція — послідовні кроки виконання дії, зазвичай у наказовому способі.",
        ["Інструкція", "кроки"])]),

    L(40, 259, CH3, "czesci-zdania",
      ("Części zdania", "Члени речення"),
      "podmiot · orzeczenie · określenia",
      ("Kto co robi i jak", "Хто що робить і як"),
      (["**Podmiot** — kto? co? **Orzeczenie** — co robi? **Przydawka** określa rzeczownik. **Dopełnienie** dopełnia czasownik. **Okolicznik** — jak, gdzie, kiedy.",
        "Wykres zdania pojedynczego pomaga zobaczyć związki."],
       ["**Підмет**, **присудок**, **означення**, **додаток**, **обставина**."]),
      goals(("wskazać podmiot i orzeczenie", "вказати підмет і присудок"),
            ("odróżnić przydawkę, dopełnienie i okolicznik na prostym przykładzie",
             "відрізнити означення, додаток і обставину")),
      [concept("Pytania pomocnicze", "Допоміжні питання",
               ["Pies szczeka. Pies = podmiot, szczeka = orzeczenie.",
                "Mały pies głośno szczeka wieczorem. mały = przydawka, głośno = okolicznik sposobu, wieczorem = okolicznik czasu."],
               ["Пес гавкає. Пес = підмет, гавкає = присудок."])],
      choice(40, "Co jest orzeczeniem w: Siostra czyta książkę.?",
             "Що є присудком у: Siostra czyta książkę.?",
             [("Siostra", "Siostra"), ("czyta", "czyta"), ("książkę", "książkę")],
             "b", "czyta = co robi?", "czyta = що робить?"),
      fill(40, "Jak nazywamy część zdania odpowiadającą na kto? co? przy orzeczeniu?",
           "Як називаємо член речення на хто? що? при присудку?",
           ["podmiot", "підмет"], "Podmiot.", "Підмет."),
      wrong("„Przydawka zawsze określa czasownik, nigdy rzeczownik.”",
            "«Означення завжди стосується дієслова, ніколи іменника.»",
            ["Przydawka określa rzeczownik (jaki pies?)."],
            ["Означення стосується іменника (який пес?)."]),
      oral(40, "W zdaniu Chłopiec kopie piłkę na boisku wskaż podmiot, orzeczenie, dopełnienie.",
           "У реченні вкажи підмет, присудок, додаток.",
           "Co określa okolicznik?",
           "Що означає обставина?",
           [("okoliczności: jak, gdzie, kiedy, dlaczego",
             "обставини: як, де, коли, чому"),
            ("tylko rodzajnik", "лише артикль"),
            ("mit o Prometeuszu", "міф про Прометея")],
           "a", "Okoliczności czynności.", "Обставини дії."),
      [("Podmiot i orzeczenie to rdzeń zdania. Przydawka, dopełnienie i okolicznik je rozwijają.",
        ["Podmiot", "orzeczenie", "Przydawka", "Dopełnienie", "Okolicznik"],
        "Підмет і присудок — стрижень речення. Означення, додаток і обставина його розвивають.",
        ["Підмет", "присудок"])]),

    L(41, 262, CH3, "streszczenie",
      ("Streszczenie", "Стислий переказ"),
      "krótko · kolejność · bez ozdób",
      ("To samo, krócej", "Те саме, коротше"),
      (["**Streszczenie** oddaje treść **własnymi słowami**, w kolejności, bez dialogów „dla klimatu” i bez własnej oceny.",
        "To nie notatka z trzech słów i nie recenzja „podobało mi się”."],
       ["**Стислий переказ** передає зміст **своїми словами**, по порядку, без оцінки."]),
      goals(("odróżnić streszczenie od recenzji", "відрізнити стислий переказ від рецензії"),
            ("pominąć szczegóły uboczne", "пропустити побічні деталі")),
      [concept("Co zostawić", "Що залишити",
               ["Kto, gdzie, co się stało, czym się skończyło.",
                "Wyrzucasz opisy pogody, jeśli nie zmieniają fabuły."],
               ["Хто, де, що сталося, чим скінчилося."])],
      choice(41, "Co należy do streszczenia?", "Що входить до стислого переказу?",
             [("własna ocena: super książka", "власна оцінка: супер книжка"),
              ("kolejne ważne zdarzenia własnymi słowami",
               "послідовні важливі події своїми словами"),
              ("wszystkie dymki z komiksu słowo w słowo",
               "усі хмарки з коміксу слово в слово")],
             "b", "Fabuła krótko, swoimi słowami.", "Фабула коротко, своїми словами."),
      fill(41, "Jak nazywamy krótki przekaz treści utworu własnymi słowami?",
           "Як називаємо коротку передачу змісту твору своїми словами?",
           ["streszczenie", "стислий переказ"], "Streszczenie.", "Стислий переказ."),
      wrong("„Streszczenie to miejsce, gdzie wpisujesz, czy lubisz bohatera.”",
            "«Стислий переказ — місце, де пишеш, чи любиш героя.»",
            ["Ocena to recenzja. Streszczenie = treść."],
            ["Оцінка — рецензія. Переказ = зміст."]),
      oral(41, "Streszcz w trzech zdaniach bajkę, którą znasz.",
           "Стисло перекажи в трьох реченнях байку, яку знаєш.",
           "Czego nie wstawiasz do streszczenia?",
           "Чого не вставляєш у стислий переказ?",
           [("własnej oceny i zbędnych ozdób", "власної оцінки і зайвих прикрас"),
            ("kolejności zdarzeń", "послідовності подій"),
            ("informacji, kto działa", "інформації, хто діє")],
           "a", "Bez recenzji.", "Без рецензії."),
      [("Streszczenie oddaje ważne zdarzenia własnymi słowami, w kolejności, bez oceny.",
        ["Streszczenie", "własnymi słowami"],
        "Стислий переказ передає важливі події своїми словами, по порядку, без оцінки.",
        ["Стислий переказ"])]),

    L(42, 300, CH3, "dialog-i-przypowiesc",
      ("Dialog i przypowieść", "Діалог і притча"),
      "głosy · morał",
      ("Rozmowa i pouczenie", "Розмова і повчання"),
      (["Wracają **dialog** (zapis od myślnika) i **przypowieść** (sens przenośny).",
        "W podręczniku m.in. utwory o relacjach ludzi — czytasz w klasie."],
       ["Повертаються **діалог** і **притча**."]),
      goals(("poprawnie zapisać krótką rozmowę", "правильно записати коротку розмову"),
            ("odczytać morał przypowieści", "зчитати мораль притчі")),
      [concept("Dwa narzędzia", "Два знаряддя",
               ["Dialog pokazuje spór albo zgodę głosami.",
                "Przypowieść pokazuje spór obrazem i morałem — jak na lekcji 7."],
               ["Діалог показує суперечку голосами. Притча — образом і мораллю."])],
      choice(42, "Który zapis dialogu jest poprawny?", "Який запис діалогу правильний?",
             [("— Czy wrócisz jutro? — zapytał brat.",
               "— Чи повернешся завтра? — запитав брат."),
              ("Czy wrócisz jutro zapytał brat bez myślników i znaków",
               "Чи повернешся завтра запитав брат без тире"),
              ("(dymek) czy wrócisz", "(хмарка) чи повернешся")],
             "a", "Myślnik + kwestia.", "Тире + репліка."),
      fill(42, "Jak nazywamy pouczenie wynikające z przypowieści?",
           "Як називаємо повчання з притчі?",
           ["morał", "мораль"], "Morał.", "Мораль."),
      wrong("„W dialogu wszystkie osoby mówią w jednym wierszu bez myślników.”",
            "«У діалозі всі особи говорять в одному рядку без тире.»",
            ["Nowa osoba — nowy wiersz i myślnik."],
            ["Нова особа — новий рядок і тире."]),
      oral(42, "Ułóż dwie kwestie dialogu i jedno zdanie morału do krótkiej historii o kłamstwie.",
           "Склади дві репліки і одне речення моралі до короткої історії про брехню.",
           "Czym różni się dialog od przypowieści?",
           "Чим діалог відрізняється від притчі?",
           [("dialog to głosy bohaterów; przypowieść to obraz z morałem",
             "діалог — голоси героїв; притча — образ з мораллю"),
            ("to zawsze to samo słowo", "це завжди те саме слово"),
            ("dialog to liczebnik", "діалог — числівник")],
           "a", "Głosy vs pouczający obraz.", "Голоси проти повчального образу."),
      [("Dialog zapisujemy od myślnika. Przypowieść niesie morał.",
        ["Dialog", "myślnika", "Przypowieść", "morał"],
        "Діалог записуємо з тире. Притча несе мораль.",
        ["Діалог", "Притча"])]),

    L(43, 328, CH4, "tworca-i-dzielo",
      ("Twórca i dzieło", "Творець і твір"),
      "autor · odbiorca · dzieło",
      ("Kto tworzy, kto ogląda", "Хто творить, хто дивиться"),
      (["Teatr, kino, muzeum, książka — wszędzie jest **twórca**, **dzieło** i **odbiorca**.",
        "Zasady miejsca: w teatrze nie rozmawiamy przez cały spektakl, w muzeum nie dotykamy obrazu."],
       ["Театр, кіно, музей, книжка — скрізь є **творець**, **твір** і **одержувач**."]),
      goals(("nazwać twórcę, dzieło i odbiorcę", "назвати творця, твір і одержувача"),
            ("podać jedną zasadę zachowania wobec dzieła", "назвати одне правило поведінки щодо твору")),
      [concept("Trójkąt kultury", "Трикутник культури",
               ["Reżyser / pisarz / malarz = twórca. Spektakl / książka / obraz = dzieło. Widz / czytelnik = odbiorca.",
                "Opinia o dziele to nie to samo co streszczenie."],
               ["Режисер / письменник = творець. Вистава / книжка = твір. Глядач / читач = одержувач."])],
      choice(43, "Kim jest odbiorca spektaklu?", "Хто є одержувачем вистави?",
             [("widz", "глядач"), ("zawsze tylko krawiec kostiumów", "завжди лише кравець костюмів"),
              ("wyłącznie rzeczownik w wołaczu", "виключно іменник у кличному")],
             "a", "Widz ogląda dzieło.", "Глядач дивиться твір."),
      fill(43, "Jak nazywamy osobę, która stworzyła utwór lub spektakl?",
           "Як називаємо особу, яка створила твір або виставу?",
           ["twórca", "autor", "творець", "автор"], "Twórca / autor.", "Творець / автор."),
      wrong("„W muzeum wolno jeść na obrazie, bo to przecież papier.”",
            "«У музеї можна їсти на картині, бо це папір.»",
            ["Dzieło jest chronione. Odbiorca ma zasady."],
            ["Твір охороняють. Одержувач має правила."]),
      oral(43, "Podaj przykład: twórca, dzieło, odbiorca (teatr albo książka).",
           "Наведи приклад: творець, твір, одержувач.",
           "Co łączy teatr, kino i muzeum na tej lekcji?",
           "Що єднає театр, кіно і музей на цьому уроці?",
           [("wszędzie jest twórca, dzieło i odbiorca",
             "скрізь є творець, твір і одержувач"),
            ("wszędzie piszemy tylko liczebniki", "скрізь пишемо лише числівники"),
            ("nigdzie nie ma zasad", "ніде немає правил")],
           "a", "Trójkąt kultury.", "Трикутник культури."),
      [("Twórca tworzy dzieło, odbiorca je odbiera. W teatrze, kinie i muzeum obowiązują zasady.",
        ["Twórca", "dzieło", "odbiorca"],
        "Творець створює твір, одержувач його сприймає. У театрі, кіно і музеї є правила.",
        ["Творець", "твір", "одержувач"])]),

    L(44, 331, CH4, "herbert-wyobraznia",
      ("Wyobraźnia. Herbert", "Уява. Герберт"),
      "obrazy w głowie",
      ("Pudełko zwane wyobraźnią", "Коробка на ім’я уява"),
      (["Zbigniew Herbert, «Pudełko zwane wyobraźnią» — autor z podstawy. Czytasz wiersz w podręczniku.",
        "Tu: **wyobraźnia** składa obrazy, których nie ma na zdjęciu."],
       ["Збігнєв Герберт — автор з програми. Вірш читаєш у підручнику.",
        "Тут: **уява** складає образи, яких немає на фото."]),
      goals(("powiedzieć, czym jest wyobraźnia w czytaniu poezji",
             "сказати, чим є уява в читанні поезії"),
            ("odróżnić obraz poetycki od fotografii-dokumentu",
             "відрізнити поетичний образ від фото-документа")),
      [concept("Co robi wyobraźnia?", "Що робить уява?",
               ["Łączy rzeczy, których świat „na serio” nie stawia obok siebie.",
                "Podmiot liryczny (lekcja 5) może otwierać takie pudełko."],
               ["Поєднує речі, яких світ «серйозно» не ставить поруч."])],
      choice(44, "Co robi wyobraźnia przy wierszu?", "Що робить уява при вірші?",
             [("składa obrazy w głowie czytelnika", "складає образи в голові читача"),
              ("zastępuje słownik ortograficzny zawsze", "завжди замінює орфографічний словник"),
              ("liczy pole rombu", "рахує площу ромба")],
             "a", "Obrazy, nie linijka.", "Образи, не лінійка."),
      fill(44, "Podaj nazwisko poety, autora «Pudełka zwanego wyobraźnią»",
           "Подай прізвище поета, автора «Коробки на ім’я уява»",
           ["Herbert", "Zbigniew Herbert", "Герберт"], "Herbert.", "Герберт."),
      wrong("„Wyobraźnia na lekcji polskiego jest zakazana, wolno tylko przepisywać definicje.”",
            "«Уява на уроці польської заборонена.»",
            ["Poezja bez wyobraźni nie działa. Definicje są po to, by mówić o obrazach."],
            ["Поезія без уяви не діє."]),
      oral(44, "Opisz obraz, który stoi ci w głowie po słowie pudełko albo gwiazda.",
           "Опиши образ, який стає в голові після слова pudełko або gwiazda.",
           "Kim jest autor omawianego wiersza?",
           "Хто автор обговорюваного вірша?",
           [("Zbigniew Herbert", "Збігнєв Герберт"),
            ("Juliusz Verne", "Жуль Верн"),
            ("Marcin Braun", "Марцін Браун")],
           "a", "Herbert.", "Герберт."),
      [("Wyobraźnia składa obrazy przy czytaniu poezji. W podręczniku: wiersz Zbigniewa Herberta.",
        ["Wyobraźnia", "Herberta"],
        "Уява складає образи при читанні поезії. У підручнику: вірш Збігнєва Герберта.",
        ["Уява", "Герберта"])]),

    L(45, 336, CH4, "zaproszenie",
      ("Zaproszenie", "Запрошення"),
      "kto · kogo · dokąd · kiedy",
      ("Proszę przyjdź", "Прошу прийди"),
      (["**Zaproszenie** ma: kto zaprasza, kogo, na co, gdzie, kiedy.",
        "Układ graficzny jest ważny — jak plakat, tylko krócej."],
       ["**Запрошення** має: хто, кого, на що, де, коли."]),
      goals(("wymienić elementy zaproszenia", "назвати елементи запрошення"),
            ("odróżnić zaproszenie od ogłoszenia", "відрізнити запрошення від оголошення")),
      [concept("Komplet danych", "Повний набір",
               ["Bez daty gość nie wie, kiedy przyjść. Bez miejsca — gdzie.",
                "Ton: serdeczny albo oficjalny, zależnie od odbiorcy."],
               ["Без дати гість не знає, коли прийти."])],
      choice(45, "Czego nie może braknąć w zaproszeniu na akademię?",
             "Чого не може бракувати в запрошенні на академію?",
             [("miejsca i terminu", "місця і терміну"),
              ("wykresu zdania złożonego", "схеми складеного речення"),
              ("mitu o Heliosie jako jedynej treści", "міфу про Геліоса як єдиного змісту")],
             "a", "Gdzie i kiedy.", "Де і коли."),
      fill(45, "Jak nazywamy tekst, który prosi kogoś, by przyszedł na wydarzenie?",
           "Як називаємо текст, який просить когось прийти на подію?",
           ["zaproszenie", "запрошення"], "Zaproszenie.", "Запрошення."),
      wrong("„Wystarczy napisać przyjdź, reszta się domyśli godziny i sali.”",
            "«Досить написати przyjdź, решту здогадаються.»",
            ["Bez gdzie i kiedy zaproszenie nie działa."],
            ["Без де і коли запрошення не діє."]),
      oral(45, "Wymień na głos pięć elementów zaproszenia.",
           "Назви вголос п’ять елементів запрошення.",
           "Czym zaproszenie różni się od instrukcji?",
           "Чим запрошення відрізняється від інструкції?",
           [("prosi, by przyjść; instrukcja uczy, jak wykonać czynność",
             "просить прийти; інструкція вчить, як виконати дію"),
            ("to zawsze to samo", "це завжди те саме"),
            ("zaproszenie odmienia się przez 17 przypadków",
             "запрошення відмінюється за 17 відмінками")],
           "a", "Przyjdź vs zrób krok po kroku.", "Прийди проти зроби крок за кроком."),
      [("Zaproszenie podaje: kto, kogo, na co, gdzie, kiedy.",
        ["Zaproszenie", "gdzie", "kiedy"],
        "Запрошення подає: хто, кого, на що, де, коли.",
        ["Запрошення", "де", "коли"])]),

    L(46, 342, CH4, "teatr-i-film",
      ("Teatr i film", "Театр і кіно"),
      "scena · kadr",
      ("Na żywo i na ekranie", "Наживо і на екрані"),
      (["**Teatr**: aktorzy na scenie, tu i teraz, oklaski.",
        "**Film**: kadr, montaż, dubbing albo napisy. Inny język opowieści."],
       ["**Театр**: актори на сцені, тут і тепер.",
        "**Фільм**: кадр, монтаж."]),
      goals(("odróżnić spektakl od filmu", "відрізнити виставу від фільму"),
            ("podać jedną cechę każdego", "назвати одну рису кожного")),
      [concept("Dwa języki", "Дві мови",
               ["W teatrze nie ma „powtórki kadru” — pomyłka zostaje w wieczorze.",
                "W filmie reżyser tnie ujęcia. Widz jest dalej od ciała aktora."],
               ["У театрі немає «повтору кадру». У фільмі режисер ріже уривки."])],
      choice(46, "Co jest cechą teatru, nie filmu?", "Що є рисою театру, не фільму?",
             [("aktorzy grają na żywo przed widownią", "актори грають наживо перед залом"),
              ("zawsze tylko montaż z tysiąca dubli jako jedyna możliwość",
               "завжди лише монтаж з тисячі дублів як єдина можливість"),
              ("brak jakiegokolwiek twórcy", "відсутність будь-якого творця")],
             "a", "Żywa scena.", "Жива сцена."),
      fill(46, "Jak nazywamy jedną „klatkę” obrazu w filmie? (jak w komiksie bywa kadr)",
           "Як називаємо один «кадр» образу у фільмі?",
           ["kadr", "ujęcie", "кадр"], "Kadr / ujęcie.", "Кадр."),
      wrong("„Film i teatr to to samo, bo oba mają popcorn.”",
            "«Фільм і театр — те саме, бо в обох є попкорн.»",
            ["Inny kontakt z aktorem, inny montaż czasu."],
            ["Інший контакт з актором, інший монтаж часу."]),
      oral(46, "Powiedz jedną zaletę teatru i jedną zaletę filmu.",
           "Скажи одну перевагу театру і одну перевагу фільму.",
           "Kto w filmie składa ujęcia w całość (zawód)?",
           "Хто у фільмі складає уривки в ціле (професія)?",
           [("reżyser (i montażysta)", "режисер (і монтажер)"),
            ("tylko liczebnik porządkowy", "лише порядковий числівник"),
            ("Demeter", "Деметра")],
           "a", "Reżyseria / montaż.", "Режисура / монтаж."),
      [("Teatr dzieje się na żywo na scenie. Film składa kadry i montaż.",
        ["Teatr", "na żywo", "Film", "kadry"],
        "Театр діється наживо на сцені. Фільм складає кадри і монтаж.",
        ["Театр", "Фільм"])]),

    L(47, 345, CH4, "akcent",
      ("Akcent", "Наголос"),
      "przedostatnia",
      ("Którą sylabę wzmacniamy", "Який склад підсилюємо"),
      (["W polskim akcent zwykle pada na **przedostatnią** sylabę: ko-LE-ga, szko-ŁA.",
        "Wyjątki (np. niektóre liczby, formy czasu przeszłego) uczysz się z listą nauczyciela i słuchem."],
       ["У польській наголос зазвичай на **передостанньому** складі."]),
      goals(("postawić akcent na przedostatniej w typowym wyrazie",
             "поставити наголос на передостанньому в типовому слові"),
            ("nie mylić akcentu z apostrofą", "не плутати наголос з апострофою")),
      [concept("Przedostatnia", "Передостання",
               ["W **szko-ła**, **ko-le-ga** wzmacniamy przedostatnią sylabę.",
                "Wyjątki uczysz się ze słuchu i ze słownika. Akcent to nie apostrofa."],
               ["У більшості слів посилюємо передостанній склад. Винятки — зі слуху і словника."])],
      choice(47, "Gdzie najczęściej pada akcent w polskim?",
             "Де найчастіше падає наголос у польській?",
             [("na przedostatniej sylabie", "на передостанньому складі"),
              ("zawsze na pierwszej literze alfabetu", "завжди на першій літері абетки"),
              ("nigdy, polski nie ma sylab", "ніколи, польська не має складів")],
             "a", "Przedostatnia.", "Передостання."),
      fill(47, "Na którą sylabę najczęściej pada akcent? (przedostatnią)",
           "На який склад найчастіше падає наголос? (przedostatnią)",
           ["przedostatnią", "przedostatnia", "передостанню", "передостанній"],
           "Przedostatnią.", "Передостанній."),
      wrong("„Akcent to to samo co apostrofa w wierszu.”",
            "«Наголос — те саме, що апострофа у вірші.»",
            ["Akcent = sylaba. Apostrofa = zwrot."],
            ["Наголос = склад. Апострофа = звертання."]),
      oral(47, "Powiedz głośno: kolega, szkoła, uczeń — zaznacz wzmocnioną sylabę.",
           "Скажи вголос: kolega, szkoła, uczeń — познач посилений склад.",
           "Co to akcent wyrazowy?",
           "Що таке словесний наголос?",
           [("wzmocnienie jednej sylaby w wyrazie", "посилення одного складу в слові"),
            ("znak zapytania", "знак питання"),
            ("rodzaj bajki", "вид байки")],
           "a", "Wzmocniona sylaba.", "Посилений склад."),
      [("W polskim akcent zwykle pada na przedostatnią sylabę.",
        ["akcent", "przedostatnią"],
        "У польській наголос зазвичай падає на передостанній склад.",
        ["наголос", "передостанній"])]),

    L(48, 357, CH4, "srodki-stylistyczne",
      ("Środki stylistyczne", "Стилістичні засоби"),
      "epitet · porównanie · przenośnia",
      ("Ozdoby sensu", "Прикраси сенсу"),
      (["**Epitet** — określenie artystyczne (srebrzysty księżyc).",
        "**Porównanie** — jak / niczym. **Przenośnia** (metafora) mówi, że coś **jest** czymś, bez jak."],
       ["**Епітет**, **порівняння**, **метафора**."]),
      goals(("odróżnić porównanie od metafory", "відрізнити порівняння від метафори"),
            ("wskazać epitet", "вказати епітет")),
      [concept("Trzy środki", "Три засоби",
               ["Porównanie: szybki jak wiatr.",
                "Metafora: wiatr to posłaniec zimy.",
                "Uosobienie z lekcji 16 też jest środkiem: wiatr szepcze."],
               ["Порівняння: jak. Метафора: без jak, tożsamość obrazu."])],
      choice(48, "Które zdanie ma porównanie?", "Яке речення має порівняння?",
             [("Jest szybki jak wiatr.", "Він швидкий, як вітер."),
              ("Wiatr to posłaniec.", "Вітер — посланець."),
              ("Wiatr — rzeczownik.", "Вітер — іменник.")],
             "a", "jak = porównanie.", "jak = порівняння."),
      fill(48, "Jak nazywamy artystyczne określenie rzeczownika (np. srebrzysty księżyc)?",
           "Як називаємо художнє означення іменника (srebrzysty księżyc)?",
           ["epitet", "епітет"], "Epitet.", "Епітет."),
      wrong("„Metafora zawsze musi mieć słowo jak.”",
            "«Метафора завжди мусить мати слово jak.»",
            ["jak jest w porównaniu. Metafora łączy bez jak."],
            ["jak є в порівнянні. Метафора — без jak."]),
      oral(48, "Ułóż porównanie i metaforę o nocy albo o rzece.",
           "Склади порівняння і метафору про ніч або річку.",
           "Czym epitet różni się od zwykłego przymiotnika w zdaniu szkolnym „duży dom”?",
           "Чим епітет відрізняється від звичайного прикметника «duży dom»?",
           [("epitet jest dobrany artystycznie, nie tylko informuje o rozmiarze",
             "епітет дібраний художньо, не лише інформує про розмір"),
            ("epitet to zawsze liczebnik", "епітет — завжди числівник"),
            ("nie ma różnicy nigdy", "різниці ніколи немає")],
           "a", "Funkcja artystyczna.", "Художня функція."),
      [("Epitet określa artystycznie. Porównanie używa jak. Metafora mówi, że coś jest czymś.",
        ["Epitet", "Porównanie", "jak", "Metafora"],
        "Епітет означає художньо. Порівняння вживає jak. Метафора каже, що щось є чимось.",
        ["Епітет", "Порівняння", "Метафора"])]),

    L(49, 360, CH4, "ogloszenie-i-cytat",
      ("Ogłoszenie i cytat", "Оголошення і цитата"),
      "fakt · « »",
      ("Informuję i cytuję", "Інформую і цитую"),
      (["**Ogłoszenie**: krótko, konkret, dane (co, gdzie, kiedy, kto).",
        "**Cytat**: cudze słowa w **cudzysłowie**, ze wskazaniem autora, gdy trzeba."],
       ["**Оголошення**: коротко, конкретно.",
        "**Цитата**: чужі слова в **лапках**."]),
      goals(("napisać szkielet ogłoszenia", "написати каркас оголошення"),
            ("wstawić cytat w cudzysłów", "вставити цитату в лапки")),
      [concept("Dwa gatunki użytkowe", "Два користувацькі жанри",
               ["Ogłoszenie nie jest wierszem. Cytat nie jest parafrazą: nie zmieniamy słów autora.",
                "W zeszycie: «…» — polskie cudzysłowy."],
               ["Оголошення не є віршем. Цитату не перефразовуємо."])],
      choice(49, "Jak zapisujemy cytat?", "Як записуємо цитату?",
             [("w cudzysłowie, bez zmiany słów", "у лапках, без зміни слів"),
              ("bez znaków, dowolnie przekręcone", "без знаків, довільно перекручені"),
              ("tylko jako dymek komiksu", "лише як хмарка коміксу")],
             "a", "Cudzysłów + wierność.", "Лапки + вірність."),
      fill(49, "Jak nazywamy krótką informację o wydarzeniu lub rzeczy do ogłoszenia publicznie?",
           "Як називаємо коротку інформацію про подію або річ для публічного повідомлення?",
           ["ogłoszenie", "оголошення"], "Ogłoszenie.", "Оголошення."),
      wrong("„Cytat wolno poprawiać, żeby ładniej brzmiał, i nie stawiać cudzysłowu.”",
            "«Цитату можна правити, щоб гарніше звучала, і не ставити лапок.»",
            ["Cytat jest wierny i oznaczony."],
            ["Цитата вірна і позначена."]),
      oral(49, "Ułóż ogłoszenie o zbiórce zeszytów (co, gdzie, kiedy).",
           "Склади оголошення про збір зошитів (що, де, коли).",
           "Czym ogłoszenie różni się od zaproszenia?",
           "Чим оголошення відрізняється від запрошення?",
           [("ogłoszenie informuje szerzej; zaproszenie prosi konkretną osobę, by przyszła",
             "оголошення інформує ширше; запрошення просить конкретну особу прийти"),
            ("nie różni się niczym", "нічим не різниться"),
            ("ogłoszenie to zawsze epopeja", "оголошення — завжди епопея")],
           "a", "Informacja vs prośba o przyjście.", "Інформація проти прохання прийти."),
      [("Ogłoszenie jest krótkie i konkretne. Cytat zapisujemy w cudzysłowie, wiernie.",
        ["Ogłoszenie", "Cytat", "cudzysłowie"],
        "Оголошення коротке і конкретне. Цитату записуємо в лапках, вірно.",
        ["Оголошення", "Цитата"])]),

    L(50, 380, CH4, "opis-dziela",
      ("Opis dzieła", "Опис твору"),
      "co widać · wrażenie",
      ("Od szczegółu do całości", "Від деталі до цілого"),
      (["**Opis dzieła** (obrazu, budowli, rzeźby): najpierw to, **co widać**, potem wrażenie.",
        "Kolejność: temat, plan (przód / tył), barwy, nastrój. Bez zmyślania faktów o autorze, jeśli ich nie znasz."],
       ["**Опис твору**: спочатку **що видно**, потім враження."]),
      goals(("ułożyć opis od ogółu do szczegółu albo odwrotnie, ale konsekwentnie",
             "скласти опис від загального до деталі або навпаки, але послідовно"),
            ("odróżnić fakt (widać czerwony dach) od opinii (ładny)",
             "відрізнити факт від думки")),
      [concept("Patrzę, potem czuję", "Дивлюсь, потім відчуваю",
               ["Fakt: na pierwszym planie stoi most.",
                "Wrażenie: obraz jest spokojny / dynamiczny.",
                "To wraca do lekcji 3: fakt i opinia."],
               ["Факт: на першому плані міст. Враження: спокійний / динамічний."])],
      choice(50, "Które zdanie jest faktem w opisie obrazu?",
             "Яке речення є фактом в описі картини?",
             [("Na pierwszym planie widać rzekę.", "На першому плані видно річку."),
              ("To najpiękniejszy obraz świata.", "Це найгарніша картина світу."),
              ("Autor na pewno był smutny w ten wtorek.",
               "Автор точно був сумний того вівторка.")],
             "a", "To, co widać.", "Те, що видно."),
      fill(50, "Jak nazywamy wypowiedź, która przedstawia wygląd obrazu lub budowli?",
           "Як називаємо висловлювання, яке показує вигляд картини або будівлі?",
           ["opis", "opis dzieła", "опис"], "Opis.", "Опис."),
      wrong("„W opisie dzieła wolno wymyślić, że w tle stoi autobus, jeśli go nie widać, byle ładnie.”",
            "«В описі твору можна вигадати автобус, якого не видно.»",
            ["Opis trzyma się tego, co na dziele. Wrażenie oddzielasz od faktu."],
            ["Опис тримається того, що на творі."]),
      oral(50, "Opisz w trzech zdaniach dobrze znany ci budynek albo obraz: co widać, potem wrażenie.",
           "Опиши в трьох реченнях знайому будівлю або картину: що видно, потім враження.",
           "W jakiej kolejności wygodnie pisać opis?",
           "В якій послідовності зручно писати опис?",
           [("najpierw to, co widać, potem wrażenie",
             "спочатку те, що видно, потім враження"),
            ("najpierw morał bajki, potem liczebnik",
             "спочатку мораль байки, потім числівник"),
            ("tylko tryb przypuszczający", "лише умовний спосіб")],
           "a", "Widok, potem odczucie.", "Вигляд, потім враження."),
      [("Opis dzieła najpierw mówi, co widać, potem wrażenie. Fakt oddzielamy od opinii.",
        ["Opis dzieła", "co widać", "wrażenie"],
        "Опис твору спочатку каже, що видно, потім враження. Факт відділяємо від думки.",
        ["Опис твору", "що видно", "враження"])]),
]

