# -*- coding: utf-8 -*-
from _catalog import CH1, CH2, CH3, CH4, L, goals, concept, choice, fill, oral, wrong

MORE = [
    L(
        6, 20, CH1, "pisownia-rz-niewymienne",
        ("Pisownia rz niewymiennego", "Написання rz без заміни"),
        "rz po ż, sz, ż…",
        ("Gdy nie ma wymiany na r", "Коли немає заміни на r"),
        (
            ["Nie każde **rz** da się sprawdzić przez **r**. Wtedy uczymy się typowych grup i wyjątków.",
             "W podręczniku jest historyjka o rzeźbiarce z okolic Rzeszowa — my ćwiczymy zasadę, bez cytatu."],
            ["Не кожне **rz** можна перевірити через **r**. Тоді вчимо типові групи і винятки.",
             "У підручнику є історія про скульпторку з-під Жешува — ми вчимо правило, без цитати."],
        ),
        goals(
            ("rozpoznać rz, którego nie sprawdzamy przez r", "розпізнати rz, якого не перевіряємо через r"),
            ("pamiętać częste grupy: rz po spółgłoskach", "пам’ятати часті групи: rz після приголосних"),
            ("sięgnąć do słownika przy wątpliwości", "звернутися до словника при сумніві"),
        ),
        [
            concept("Rz niewymienne", "Незмінне rz",
                    ["**Rz niewymienne** nie ma pary z **r** w wyrazie pokrewnym.",
                     "Często po: **b, p, d, t, g, k, ch, j, w** — np. **grzyb, krzyż, brzeg** (sprawdzasz w słowniku, gdy niepewny).",
                     "Czasowniki typu **marzyć, tworzyć** też warto zapamiętać."],
                    ["**Незмінне rz** не має пари з **r** у спорідненому слові.",
                     "Часто після: **b, p, d, t, g, k, ch, j, w**.",
                     "Дієслова на кшталт **marzyć, tworzyć** варто запам’ятати."]),
        ],
        choice(6, "Które stwierdzenie jest prawdziwe?", "Яке твердження правильне?",
               [("Każde rz wymieniamy na r", "Кожне rz міняємо на r"),
                ("Są wyrazy z rz, których nie sprawdzamy przez r",
                 "Є слова з rz, яких не перевіряємо через r"),
                ("rz i ż to ten sam dźwięk, więc piszemy jak chcemy",
                 "rz і ż — той самий звук, тож пишемо як хочемо")],
               "b", "Niewymienne rz uczymy się i sprawdzamy w słowniku.",
               "Незмінне rz вчимо і перевіряємо в словнику."),
        fill(6, "Jaką dwuzgłoskę piszemy w wyrazie grzyb? (dwie litery)",
             "Який диграф пишемо в слові grzyb? (дві літери)",
             ["rz"], "grzyb — rz niewymienne.", "grzyb — незмінне rz."),
        wrong("„Skoro słyszę ż, zawsze piszę ż.”",
              "«Якщо чую ż, завжди пишу ż.»",
              ["Ten sam dźwięk bywa rz albo ż. Trzeba zasady albo słownika."],
              ["Той самий звук буває rz або ż. Потрібне правило або словник."]),
        oral(6, "Wymień dwa wyrazy z rz, którego nie sprawdzasz przez r.",
             "Назви два слова з rz, якого не перевіряєш через r.",
             "Co robisz, gdy nie znasz pisowni rz?",
             "Що робиш, коли не знаєш написання rz?",
             [("Sprawdzam zasadę grupy i słownik", "Перевіряю правило групи і словник"),
              ("Zawsze stawiam ż", "Завжди ставлю ż"),
              ("Pomijam literę", "Пропускаю літеру")],
             "a", "Zasada + słownik.", "Правило + словник."),
        [
            ("Nie każde rz sprawdzamy przez r — bywa rz niewymienne.",
             ["rz niewymienne"],
             "Не кожне rz перевіряємо через r — буває незмінне rz.",
             ["незмінне rz"]),
            ("Przy wątpliwości korzystamy ze słownika ortograficznego.",
             ["słownika ortograficznego"],
             "При сумніві користуємося орфографічним словником.",
             ["орфографічним словником"]),
        ],
    ),
    L(
        7, 26, CH1, "przypowiesc",
        ("Przypowieść", "Притча"),
        "obraz → morał",
        ("Mała historia, większy sens", "Мала історія, більший сенс"),
        (
            ["**Przypowieść** opowiada prostą historię, a znaczy więcej niż dosłownie.",
             "W podręczniku: Czesław Miłosz, «Przypowieść o maku». Tu uczymy gatunku, bez cytatu."],
            ["**Притча** розповідає просту історію, а значить більше, ніж буквально.",
             "У підручнику: Чеслав Мілош, «Przypowieść o maku». Тут учимо жанр, без цитати."],
        ),
        goals(
            ("rozpoznać przypowieść jako gatunek", "розпізнати притчу як жанр"),
            ("odróżnić sens dosłowny od przenośnego", "відрізнити буквальний сенс від переносного"),
            ("powiedzieć, po co jest morał", "сказати, навіщо мораль"),
        ),
        [
            concept("Dosłownie i przenośnie", "Буквально і переносно",
                    ["**Sens dosłowny**: co się wydarza w opowieści (np. ziarno, pole).",
                     "**Sens przenośny**: lekcja o świecie ludzi — morał.",
                     "Przypowieść jest krótka, pouczająca, często z obrazem z natury."],
                    ["**Буквальний сенс**: що відбувається в оповіді.",
                     "**Переносний сенс**: урок про світ людей — мораль.",
                     "Притча коротка, повчальна, часто з образом із природи."]),
        ],
        choice(7, "Czym jest przypowieść?", "Що таке притча?",
               [("Długi romans bez morału", "Довгий роман без моралі"),
                ("Krótka opowieść z sensem przenośnym i pouczeniem",
                 "Коротка оповідь з переносним сенсом і повчанням"),
                ("Tylko spis dat historycznych", "Лише список історичних дат")],
               "b", "Obraz + morał.", "Образ + мораль."),
        fill(7, "Jak nazywamy pouczenie wynikające z przypowieści?",
             "Як називаємо повчання, що випливає з притчі?",
             ["morał", "moral", "мораль"],
             "Morał.", "Мораль."),
        wrong("„W przypowieści liczy się tylko to, co widać dosłownie, jak w instrukcji pralki.”",
              "«У притчі важливе лише те, що видно буквально, як в інструкції до пралки.»",
              ["Przypowieść ma drugi plan: przenośnię i morał."],
              ["Притча має другий план: перенос і мораль."]),
        oral(7, "Wymień jedną cechę przypowieści.",
             "Назви одну рису притчі.",
             "Które zestawienie pasuje do przypowieści?",
             "Яке поєднання пасує до притчі?",
             [("krótka historia + sens przenośny + morał",
               "коротка історія + переносний сенс + мораль"),
              ("tylko rymy aabb", "лише рими aabb"),
              ("wykres zdania pojedynczego", "схема простого речення")],
             "a", "Gatunek pouczający.", "Повчальний жанр."),
        [
            ("Przypowieść to krótka opowieść z sensem przenośnym i morałem.",
             ["Przypowieść", "przenośnym", "morałem"],
             "Притча — коротка оповідь з переносним сенсом і мораллю.",
             ["Притча", "переносним", "мораллю"]),
        ],
    ),
    L(
        8, 28, CH1, "komiks",
        ("Komiks", "Комікс"),
        "kadr + dymki",
        ("Obraz też opowiada", "Образ теж розповідає"),
        (
            ["**Komiks** łączy rysunek i tekst. Kadr, dymki, onomatopeje — to jego język.",
             "W podręczniku fragment Asteriksa. My uczymy cech gatunku."],
            ["**Комікс** поєднує малюнок і текст. Кадр, хмарки, ономатопеї — його мова.",
             "У підручнику уривок Asteriksa. Ми вчимо риси жанру."],
        ),
        goals(
            ("wymienić cechy komiksu", "назвати риси коміксу"),
            ("odczytać emocje z dymka i rysunku", "зчитати емоції з хмарки і малюнка"),
            ("odróżnić komiks od zwykłego opowiadania", "відрізнити комікс від звичайного оповідання"),
        ),
        [
            concept("Z czego składa się komiks?", "З чого складається комікс?",
                    ["**Kadr** = jedna „klatka” obrazu. Kolejność kadrów to czas opowieści.",
                     "**Dymki** niosą mowę i myśli. Kształt dymka bywa znakiem emocji.",
                     "**Onomatopeja** naśladuje dźwięk: bum, plusk."],
                    ["**Кадр** = один «кадр» образу. Порядок кадрів — час оповіді.",
                     "**Хмарки** несуть мову і думки. Форма хмарки буває знаком емоцій.",
                     "**Ономатопея** наслідує звук: bum, plusk."]),
        ],
        choice(8, "Co jest cechą komiksu?", "Що є рисою коміксу?",
               [("Tylko suche definicje bez obrazów", "Лише сухі означення без образів"),
                ("Kadry, dymki i często onomatopeje", "Кадри, хмарки і часто ономатопеї"),
                ("Wyłącznie wykres zdania", "Виключно схема речення")],
               "b", "Komiks = obraz + tekst w kadrach.", "Комікс = образ + текст у кадрах."),
        fill(8, "Jak nazywamy jedną „klatkę” obrazu w komiksie?",
             "Як називаємо один «кадр» образу в коміксі?",
             ["kadr", "кадр"],
             "Kadr.", "Кадр."),
        wrong("„W komiksie tekst nic nie znaczy, patrzysz tylko na kolorowe obrazki.”",
              "«У коміксі текст нічого не значить, дивишся лише на кольорові малюнки.»",
              ["Tekst w dymkach i onomatopeje są częścią opowieści."],
              ["Текст у хмарках і ономатопеї є частиною оповіді."]),
        oral(8, "Opowiedz, czym kadr różni się od dymka.",
             "Розкажи, чим кадр відрізняється від хмарки.",
             "Co niesie dymek w komiksie?",
             "Що несе хмарка в коміксі?",
             [("mowę lub myśli bohatera", "мову або думки героя"),
              ("tylko numer strony podręcznika", "лише номер сторінки підручника"),
              ("wyłącznie przypadki rzeczownika", "виключно відмінки іменника")],
             "a", "Dymek = wypowiedź / myśl.", "Хмарка = висловлювання / думка."),
        [
            ("Komiks opowiada kadrami: rysunek, dymki, często onomatopeje.",
             ["kadrami", "dymki", "onomatopeje"],
             "Комікс оповідає кадрами: малюнок, хмарки, часто ономатопеї.",
             ["кадрами", "хмарки", "ономатопеї"]),
        ],
    ),
    L(
        9, 31, CH1, "mit",
        ("Mit", "Міф"),
        "bogowie · początek świata",
        ("Opowieść, która tłumaczy świat", "Оповідь, яка пояснює світ"),
        (
            ["**Mit** to dawna opowieść o bogach, herosach i początku świata.",
             "Ludzie tłumaczyli nim to, czego nie umieli zmierzyć linijką."],
            ["**Міф** — давня оповідь про богів, героїв і початок світу.",
             "Ним пояснювали те, чого не вміли виміряти лінійкою."],
        ),
        goals(
            ("powiedzieć, czym jest mit", "сказати, що таке міф"),
            ("odróżnić mit od tekstu popularnonaukowego", "відрізнити міф від науково-популярного тексту"),
            ("wskazać, że mit ma sens kulturowy, nie pomiar laboratoryjny",
             "вказати, що міф має культурний сенс, не лабораторний вимір"),
        ),
        [
            concept("Mit a nauka", "Міф і наука",
                    ["Mit **nie jest** raportem z laboratorium. To opowieść wspólnoty o porządku świata.",
                     "W Grecji mity mówią o Olimpie. Inne ludy miały inne obrazy początku.",
                     "W podręczniku czytasz mity i fragment o stworzeniu — porównujesz języki opowieści."],
                    ["Міф **не є** звітом з лабораторії. Це оповідь спільноти про лад світу.",
                     "У Греції міфи говорять про Олімп. Інші народи мали інші образи початку."]),
        ],
        choice(9, "Czym jest mit?", "Що таке міф?",
               [("Przepis kulinarny", "Кулінарний рецепт"),
                ("Dawna opowieść o bogach, herosach i początku świata",
                 "Давня оповідь про богів, героїв і початок світу"),
                ("Wykres zdania złożonego", "Схема складеного речення")],
               "b", "Mit tłumaczy świat opowieścią.", "Міф пояснює світ оповіддю."),
        fill(9, "Jak nazywamy dawną opowieść o bogach i początku świata?",
             "Як називаємо давню оповідь про богів і початок світу?",
             ["mit", "міф"],
             "Mit.", "Міф."),
        wrong("„Mit i artykuł z podręcznika geografii to to samo: oba mierzą temperaturę gwiazd.”",
              "«Міф і стаття з підручника географії — те саме: обидва міряють температуру зір.»",
              ["Mit to opowieść kulturowa. Tekst popularnonaukowy podaje sprawdzalne fakty."],
              ["Міф — культурна оповідь. Науково-популярний текст подає перевірювані факти."]),
        oral(9, "Powiedz jedną różnicę między mitem a notatką z lekcji o kosmosie.",
             "Скажи одну різницю між міфом і нотаткою з уроку про космос.",
             "Które zdanie jest prawdziwe?",
             "Яке речення правильне?",
             [("Mit tłumaczy świat opowieścią o bogach; tekst naukowy podaje fakty",
               "Міф пояснює світ оповіддю про богів; науковий текст подає факти"),
              ("Mit to to samo co dymek w komiksie", "Міф — те саме, що хмарка в коміксі"),
              ("Mitu nie wolno czytać w klasie 5", "Міф не можна читати в 5 класі")],
             "a", "Inny język opisu świata.", "Інша мова опису світу."),
        [
            ("Mit to dawna opowieść o bogach, herosach i początku świata.",
             ["Mit", "bogach", "początku świata"],
             "Міф — давня оповідь про богів, героїв і початок світу.",
             ["Міф", "богів", "початок світу"]),
        ],
    ),
    L(
        10, 34, CH1, "biblia-stworzenie",
        ("Opowieść o stworzeniu świata", "Оповідь про створення світу"),
        "święty tekst · obraz",
        ("Inny język początku", "Інша мова початку"),
        (
            ["W podręczniku jest fragment **Księgi Rodzaju** — lektura obowiązkowa. Czytasz w klasie z nauczycielem.",
             "Tu: to **święty tekst** dla chrześcijan i Żydów; mówi obrazami, nie wzorem fizyki."],
            ["У підручнику є уривок **Книги Буття** — обов’язкова лектура. Читаєш у класі з учителем.",
             "Тут: це **святий текст** для християн і євреїв; говорить образами, не формулою фізики."],
        ),
        goals(
            ("odróżnić święty tekst od mitu greckiego i od artykułu naukowego",
             "відрізнити святий текст від грецького міфу і від наукової статті"),
            ("powiedzieć, że Biblia używa obrazów", "сказати, що Біблія вживає образи"),
            ("szanować, że to tekst wiary wielu ludzi", "шанувати, що це текст віри багатьох людей"),
        ),
        [
            concept("Jak czytać ten tekst w szkole?", "Як читати цей текст у школі?",
                    ["Na lekcji polskiego patrzymy na **język i obrazy**, nie rozstrzygamy sporów wiary.",
                     "Opowieść o stworzeniu porządkuje świat: światłość, ziemia, istoty żywe.",
                     "Obok w podręczniku jest wiersz ks. Jana Twardowskiego «Który stwarzasz jagody» — wdzięczność za dar świata."],
                    ["На уроці польської дивимось на **мову і образи**, не розв’язуємо спорів віри.",
                     "Оповідь про створення впорядковує світ: світло, земля, живі істоти.",
                     "Поруч у підручнику вірш кс. Яна Твардовського «Który stwarzasz jagody»."]),
        ],
        choice(10, "Jak na lekcji polskiego czytamy fragment Księgi Rodzaju?",
               "Як на уроці польської читаємо уривок Книги Буття?",
               [("Jak wzór z fizyki do podstawienia liczb", "Як формулу з фізики для підстановки чисел"),
                ("Jako święty tekst z obrazami, z szacunkiem, pod kątem języka",
                 "Як святий текст з образами, з повагою, з погляду мови"),
                ("Jako komiks o Asteriksie", "Як комікс про Астерікса")],
               "b", "Język i szacunek, nie laboratorium.", "Мова і повага, не лабораторія."),
        fill(10, "Jak nazywa się pierwsza księga Biblii? (po polsku, dwa słowa)",
             "Як називається перша книга Біблії? (польською, два слова)",
             ["Księga Rodzaju", "ksiega rodzaju", "Rodzaju", "Книга Буття"],
             "Księga Rodzaju.", "Книга Буття (Księga Rodzaju)."),
        wrong("„Święty tekst wolno wyśmiewać tak samo jak żart z klasowego czatu.”",
              "«Святий текст можна висміювати так само, як жарт із класного чату.»",
              ["Czytamy z szacunkiem. Analiza języka nie jest kpiną."],
              ["Читаємо з повагою. Аналіз мови — не глузування."]),
        oral(10, "Powiedz, czym różni się ten tekst od mitu o Zeusie i od artykułu o planetach.",
             "Скажи, чим цей текст відрізняється від міфу про Зевса і від статті про планети.",
             "Które zestawienie jest najtrafniejsze?",
             "Яке поєднання найточніше?",
             [("Biblia — święty tekst wiary; mit grecki — opowieść o Olimpie; artykuł — fakty",
               "Біблія — святий текст віри; грецький міф — оповідь про Олімп; стаття — факти"),
              ("Wszystko to dyktando z rz", "Усе це диктант з rz"),
              ("To trzy nazwy tego samego komiksu", "Це три назви того самого коміксу")],
             "a", "Trzy różne języki mówienia o świecie.", "Три різні мови говоріння про світ."),
        [
            ("Księga Rodzaju to święty tekst. Na polskim czytamy obrazy i język z szacunkiem.",
             ["Księga Rodzaju", "święty tekst", "szacunkiem"],
             "Книга Буття — святий текст. На польській читаємо образи і мову з повагою.",
             ["Книга Буття", "святий текст", "повагою"]),
        ],
    ),
    L(
        11, 40, CH1, "demeter-i-kora",
        ("Mit o Demeter i Korze", "Міф про Деметру і Кору"),
        "matka · córka · pory roku",
        ("Dlaczego jest zima?", "Чому буває зима?"),
        (
            ["Mit o **Demeter** i **Korze** (Persefonie) tłumaczy pory roku opowieścią o matce i córce.",
             "To mit z podstawy programowej. Czytasz w podręczniku; tu — szkielet historii, bez cytatu."],
            ["Міф про **Деметру** і **Кору** (Персефону) пояснює пори року оповіддю про матір і доньку.",
             "Це міф з програми. Читаєш у підручнику; тут — каркас історії, без цитати."],
        ),
        goals(
            ("powiedzieć, kim są Demeter i Kora", "сказати, ким є Деметра і Кора"),
            ("połączyć mit z porami roku", "поєднати міф із порами року"),
            ("odróżnić ten mit od tekstu naukowego o klimacie", "відрізнити цей міф від наукового тексту про клімат"),
        ),
        [
            concept("Matka zboża, córka podziemia", "Мати збіжжя, донька підзем’я",
                    ["**Demeter** opiekuje się urodzajem. **Kora / Persefona** spędza część roku w świecie zmarłych.",
                     "Gdy córka jest z matką — ziemia rodzi. Gdy schodzi w dół — zima.",
                     "Mit nie zastępuje lekcji geografii: to obraz, nie wykres temperatury."],
                    ["**Деметра** опікується врожаєм. **Кора / Персефона** частину року проводить у світі померлих.",
                     "Коли донька з матір’ю — земля родить. Коли сходить униз — зима."]),
        ],
        choice(11, "Z czym mit o Demeter i Korze wiąże pory roku?",
               "З чим міф про Деметру і Кору пов’язує пори року?",
               [("Z obecnością córki przy matce albo w podziemiu",
                 "З присутністю доньки біля матері або в підзем’ї"),
                ("Z liczbą liter w wyrazie zima", "З кількістю літер у слові zima"),
                ("Z trybem rozkazującym czasownika", "З наказовим способом дієслова")],
               "a", "Rozłąka i powrót Kory = zima i wiosna w opowieści.",
               "Розлука і повернення Кори = зима і весна в оповіді."),
        fill(11, "Jak nazywa się bogini urodzaju, matka Kory?",
             "Як називається богиня врожаю, мати Кори?",
             ["Demeter", "demeter", "Деметра"],
             "Demeter.", "Деметра."),
        wrong("„Ten mit to instrukcja, w którym miesiącu siać pszenicę według IMGW.”",
              "«Цей міф — інструкція, в якому місяці сіяти пшеницю за гідрометцентром.»",
              ["Mit daje obraz. Kalendarz rolnika i klimat to inna wiedza."],
              ["Міф дає образ. Календар хлібороба і клімат — інше знання."]),
        oral(11, "Opowiedz mit o Demeter i Korze w trzech zdaniach.",
             "Розкажи міф про Деметру і Кору в трьох реченнях.",
             "Kiedy — według mitu — ziemia nie rodzi?",
             "Коли — за міфом — земля не родить?",
             [("gdy Kora jest w świecie zmarłych", "коли Кора у світі померлих"),
              ("gdy Demeter pisze list oficjalny", "коли Деметра пише офіційного листа"),
              ("gdy ktoś użyje apostrofy", "коли хтось уживе апострофу")],
             "a", "Rozłąka matki i córki.", "Розлука матері і доньки."),
        [
            ("Mit o Demeter i Korze tłumaczy pory roku rozłąką matki i córki.",
             ["Demeter", "Korze", "pory roku"],
             "Міф про Деметру і Кору пояснює пори року розлукою матері і доньки.",
             ["Деметру", "Кору", "пори року"]),
        ],
    ),
    L(
        12, 45, CH1, "prometeusz",
        ("Mit o Prometeuszu", "Міф про Прометея"),
        "ogień · kara · dar",
        ("Dar, który kosztował", "Дар, який коштував"),
        (
            ["**Prometeusz** przynosi ludziom ogień — i płaci za to karą.",
             "Mit o buncie, darze i cenie. W podręczniku: wersja Wandy Markowskiej."],
            ["**Прометей** приносить людям вогонь — і платить за це карою.",
             "Міф про бунт, дар і ціну. У підручнику: версія Ванди Марковської."],
        ),
        goals(
            ("powiedzieć, kim był Prometeusz i jaki dar dał ludziom", "сказати, ким був Прометей і який дар дав людям"),
            ("odróżnić dar od kary w micie", "відрізнити дар від кари в міфі"),
            ("wskazać, że mit stawia pytanie o odwagę i odpowiedzialność",
             "вказати, що міф ставить питання про відвагу і відповідальність"),
        ),
        [
            concept("Ogień i cena", "Вогонь і ціна",
                    ["Prometeusz staje po stronie ludzi. **Ogień** to dar cywilizacji: ciepło, rzemiosło.",
                     "Za złamanie woli Zeusa przychodzi **kara**.",
                     "Nie opisujemy kaźni szczegółami — liczy się wybór i konsekwencja."],
                    ["Прометей стає на бік людей. **Вогонь** — дар цивілізації: тепло, ремесло.",
                     "За порушення волі Зевса приходить **кара**.",
                     "Не описуємо кару деталями — важливим є вибір і наслідок."]),
        ],
        choice(12, "Jaki dar Prometeusz dał ludziom w micie?",
               "Який дар Прометей дав людям у міфі?",
               [("ogień", "вогонь"), ("wykres zdania", "схему речення"), ("zeszyt ćwiczeń", "зошит вправ")],
               "a", "Ogień jako dar dla ludzi.", "Вогонь як дар людям."),
        fill(12, "Jak nazywa się tytan, który dał ludziom ogień?",
             "Як називається титан, який дав людям вогонь?",
             ["Prometeusz", "prometeusz", "Прометей"],
             "Prometeusz.", "Прометей."),
        wrong("„Prometeusz dostał ogień od ludzi w prezencie na urodziny Zeusa.”",
              "«Прометей отримав вогонь від людей у подарунок на день народження Зевса.»",
              ["To Prometeusz dał ogień ludziom — i poniósł karę."],
              ["Це Прометей дав вогонь людям — і поніс кару."]),
        oral(12, "Powiedz, za co Prometeusz został ukarany.",
             "Скажи, за що Прометея покарали.",
             "Co łączy dar i karę w tym micie?",
             "Що поєднує дар і кару в цьому міфі?",
             [("dar dla ludzi łamie zakaz; kara jest konsekwencją",
               "дар людям ламає заборону; кара є наслідком"),
              ("kara to apostrofa w wierszu", "кара — апострофа у вірші"),
              ("nie ma żadnego daru", "немає жодного дару")],
             "a", "Wybór ma cenę.", "Вибір має ціну."),
        [
            ("Prometeusz dał ludziom ogień i poniósł karę za złamanie zakazu.",
             ["Prometeusz", "ogień", "karę"],
             "Прометей дав людям вогонь і поніс кару за порушення заборони.",
             ["Прометей", "вогонь", "кару"]),
        ],
    ),
    L(
        13, 50, CH1, "rzeczownik",
        ("Rzeczownik", "Іменник"),
        "kto? co?",
        ("Słowa, które nazywają", "Слова, які називають"),
        (
            ["**Rzeczownik** odpowiada na pytania **kto? co?** Nazywa osoby, rzeczy, zwierzęta, zjawiska, uczucia.",
             "Odmienia się przez przypadki i liczby. Pisownia **nie** z rzeczownikiem — zwykle osobno (wyjątki: nikt, nic, niebo…)."],
            ["**Іменник** відповідає на питання **хто? що?** Називає осіб, речі, тварин, явища, почуття.",
             "Відмінюється за відмінками і числами. **nie** з іменником — зазвичай окремо."],
        ),
        goals(
            ("rozpoznać rzeczownik w zdaniu", "розпізнати іменник у реченні"),
            ("odróżnić rzeczownik od czasownika i przymiotnika", "відрізнити іменник від дієслова і прикметника"),
            ("pamiętać o pisowni nie z rzeczownikiem", "пам’ятати про написання nie з іменником"),
        ),
        [
            concept("Kto? Co?", "Хто? Що?",
                    ["**uczeń, rzeka, radość, Warszawa** — rzeczowniki.",
                     "Nie: **biegnie** (czasownik), **ładny** (przymiotnik).",
                     "Rzeczownik ma **przypadek, liczbę, rodzaj**."],
                    ["**uczeń, rzeka, radość, Warszawa** — іменники.",
                     "Не: **biegnie** (дієслово), **ładny** (прикметник).",
                     "Іменник має **відмінок, число, рід**."]),
            concept("Nie z rzeczownikiem", "Nie з іменником",
                    ["Zwykle **osobno**: nie radość, nie uczeń.",
                     "Wyjątki-zrosty uczysz się z listą (np. niebo, nikt, nic, niemoc — sprawdzaj w słowniku)."],
                    ["Зазвичай **окремо**: nie radość, nie uczeń.",
                     "Винятки-зрощення вчиш зі списком і словником."]),
        ],
        choice(13, "Które słowo jest rzeczownikiem?", "Яке слово є іменником?",
               [("biegnie", "biegnie"), ("las", "las"), ("szybki", "szybki")],
               "b", "las = kto? co?", "las = хто? що?"),
        fill(13, "Na jakie pytania odpowiada rzeczownik? (napisz: kto? co?)",
             "На які питання відповідає іменник? (напиши: kto? co?)",
             ["kto? co?", "kto co", "kto?co?", "хто? що?", "kto?", "co?"],
             "kto? co?", "хто? що?"),
        wrong("„Rzeczownik nigdy się nie odmienia i zawsze piszemy nieuczeń razem.”",
              "«Іменник ніколи не відмінюється і завжди пишемо nieuczeń разом.»",
              ["Rzeczownik się odmienia. nie z rzeczownikiem zwykle osobno."],
              ["Іменник відмінюється. nie з іменником зазвичай окремо."]),
        oral(13, "Podaj trzy rzeczowniki: osobę, rzecz i uczucie.",
             "Назви три іменники: особу, річ і почуття.",
             "Który zestaw to same rzeczowniki?",
             "Який набір — самі іменники?",
             [("mama, stół, strach", "mama, stół, strach"),
              ("biega, ładny, bardzo", "biega, ładny, bardzo"),
              ("i, oraz, ale", "i, oraz, ale")],
             "a", "Osoba, rzecz, uczucie.", "Особа, річ, почуття."),
        [
            ("Rzeczownik odpowiada na pytania kto? co? i nazywa osoby, rzeczy, zjawiska, uczucia.",
             ["Rzeczownik", "kto? co?"],
             "Іменник відповідає на питання хто? що? і називає осіб, речі, явища, почуття.",
             ["Іменник", "хто? що?"]),
            ("nie z rzeczownikiem zwykle piszemy osobno.",
             ["nie", "osobno"],
             "nie з іменником зазвичай пишемо окремо.",
             ["nie", "окремо"]),
        ],
    ),
    L(
        14, 53, CH1, "list-i-slownik",
        ("List i słownik wyrazów bliskoznacznych", "Лист і словник синонімів"),
        "nadawca · odbiorca · synonim",
        ("Piszę do kogoś i szukam lepszego słowa", "Пишу до когось і шукаю краще слово"),
        (
            ["**List** ma nadawcę, odbiorcę, datę, zwrot, treść i podpis.",
             "**Słownik wyrazów bliskoznacznych** (synonimów) pomaga nie powtarzać tego samego słowa."],
            ["**Лист** має адресанта, адресата, дату, звертання, зміст і підпис.",
             "**Словник синонімів** допомагає не повторювати те саме слово."],
        ),
        goals(
            ("wymienić części listu", "назвати частини листа"),
            ("powiedzieć, do czego służy słownik synonimów", "сказати, навіщо словник синонімів"),
            ("zastąpić powtórzone słowo bliskoznacznym", "замінити повторене слово синонімом"),
        ),
        [
            concept("Budowa listu", "Будова листа",
                    ["Miejsce i data. Zwrot do odbiorcy. Treść. Zakończenie. Podpis.",
                     "List do kolegi brzmi inaczej niż do dyrektora — to znowu sytuacja komunikacyjna."],
                    ["Місце і дата. Звертання. Зміст. Завершення. Підпис.",
                     "Лист до друга звучить інакше, ніж до директора."]),
            concept("Wyrazy bliskoznaczne", "Синоніми",
                    ["**Dom, chatka, siedziba** — bliskie znaczeniem, ale nie zawsze pasują w tym samym zdaniu.",
                     "Słownik pomaga wybrać odcień: oficjalny albo potoczny."],
                    ["**Dom, chatka, siedziba** — близькі за значенням, але не завжди пасують у тому самому реченні."]),
        ],
        choice(14, "Czego brakuje w liście bez podpisu i zwrotu do odbiorcy?",
               "Чого бракує в листі без підпису і звертання до адресата?",
               [("elementów kompozycji listu", "елементів композиції листа"),
                ("tylko liczby π", "лише числа π"),
                ("mitu o Prometeuszu", "міфу про Прометея")],
               "a", "List ma stałe części.", "Лист має сталі частини."),
        fill(14, "Jak nazywamy wyrazy o bliskim znaczeniu?",
             "Як називаємо слова з близьким значенням?",
             ["synonimy", "wyrazy bliskoznaczne", "bliskoznaczne", "синоніми"],
             "Synonimy / wyrazy bliskoznaczne.", "Синоніми."),
        wrong("„W liście do dyrektora piszemy tak samo jak SMS do kolegi z boiska.”",
              "«У листі до директора пишемо так само, як SMS другу з поля.»",
              ["Dobieramy styl do odbiorcy i celu."],
              ["Добіраємо стиль до адресата і мети."]),
        oral(14, "Wymień po kolei części listu.",
             "Назви по черзі частини листа.",
             "Do czego służy słownik wyrazów bliskoznacznych?",
             "Навіщо словник синонімів?",
             [("żeby znaleźć inne słowo o podobnym znaczeniu",
               "щоб знайти інше слово з подібним значенням"),
              ("żeby liczyć pole trapezu", "щоб рахувати площу трапеції"),
              ("żeby zastąpić wszystkie rzeczowniki czasownikami",
               "щоб замінити всі іменники дієсловами")],
             "a", "Synonimy = bliskie znaczenia.", "Синоніми = близькі значення."),
        [
            ("List ma datę, zwrot, treść, zakończenie i podpis. Styl zależy od odbiorcy.",
             ["List", "odbiorcy"],
             "Лист має дату, звертання, зміст, завершення і підпис. Стиль залежить від адресата.",
             ["Лист", "адресата"]),
            ("Słownik wyrazów bliskoznacznych pomaga unikać powtórzeń.",
             ["bliskoznacznych", "powtórzeń"],
             "Словник синонімів допомагає уникати повторів.",
             ["синонімів", "повторів"]),
        ],
    ),
    L(
        15, 60, CH1, "odmiana-rzeczownika",
        ("Odmiana rzeczownika", "Відмінювання іменника"),
        "7 przypadków",
        ("Ten sam wyraz, inna końcówka", "Те саме слово, інше закінчення"),
        (
            ["Rzeczownik zmienia końcówkę, gdy zmienia się pytanie: kto? kogo? komu? kogo? z kim? o kim?",
             "Siedem **przypadków**. Liczba pojedyncza i mnoga."],
            ["Іменник змінює закінчення, коли змінюється питання.",
             "Сім **відмінків**. Однина і множина."],
        ),
        goals(
            ("wymienić przypadki rzeczownika", "назвати відмінки іменника"),
            ("odmienić prosty rzeczownik w liczbie pojedynczej", "відмінити простий іменник в однині"),
            ("nie pomylić mianownika z biernikiem", "не сплутати називний із знахідним"),
        ),
        [
            concept("Przypadki", "Відмінки",
                    ["Mianownik kto? co? Dopełniacz kogo? czego? Celownik komu? czemu? Biernik kogo? co? Narzędnik z kim? z czym? Miejscownik o kim? o czym? Wołacz o!",
                     "Wołacz bywa w apostrofie: Przyjacielu!"],
                    ["Називний kto? co? Родовий kogo? czego? Давальний komu? czemu? Знахідний kogo? co? Орудний z kim? z czym? Місцевий o kim? o czym? Кличний o!"]),
        ],
        choice(15, "Które pytanie pasuje do dopełniacza?", "Яке питання пасує до родового відмінка?",
               [("kto? co?", "kto? co?"), ("kogo? czego?", "kogo? czego?"), ("z kim? z czym?", "z kim? z czym?")],
               "b", "Dopełniacz: kogo? czego?", "Родовий: kogo? czego?"),
        fill(15, "Ile przypadków ma rzeczownik w polskim? (cyfra)",
             "Скільки відмінків має іменник у польській? (цифра)",
             ["7", "siedem", "сім"],
             "Siedem.", "Сім."),
        wrong("„Rzeczownik w każdym zdaniu zostaje w mianowniku, bo tak wygodniej.”",
              "«Іменник у кожному реченні лишається в називному, бо так зручніше.»",
              ["Końcówka zależy od funkcji w zdaniu i przyimka."],
              ["Закінчення залежить від функції в реченні і прийменника."]),
        oral(15, "Odmień na głos: kot — mianownik, dopełniacz, biernik (l.poj.).",
             "Відміни вголос: kot — називний, родовий, знахідний (одн.).",
             "Jaka jest forma dopełniacza od kot (l.poj.)?",
             "Яка форма родового відмінка від kot (одн.)?",
             [("kota", "kota"), ("kotem", "kotem"), ("kocie", "kocie")],
             "a", "kogo? czego? — kota", "kogo? czego? — kota"),
        [
            ("Rzeczownik odmienia się przez siedem przypadków oraz liczby.",
             ["siedem przypadków"],
             "Іменник відмінюється за сімома відмінками та числами.",
             ["сімома відмінками"]),
        ],
    ),
    L(
        16, 69, CH1, "przymiotnik-i-uosobienie",
        ("Przymiotnik i uosobienie", "Прикметник і уособлення"),
        "jaki? · jakby człowiek",
        ("Cecha i ożywienie", "Ознака і оживлення"),
        (
            ["**Przymiotnik** odpowiada na **jaki? jaka? jakie?** i się z rzeczownikiem zgadza.",
             "**Uosobienie** (personifikacja) nadaje rzeczom cechy człowieka. W podręczniku m.in. Tuwim."],
            ["**Прикметник** відповідає на **який? яка? яке?** і узгоджується з іменником.",
             "**Уособлення** надає речам риси людини. У підручнику м.in. Тувім."],
        ),
        goals(
            ("rozpoznać przymiotnik i uzgodnić go z rzeczownikiem", "розпізнати прикметник і узгодити з іменником"),
            ("wskazać uosobienie w zdaniu", "вказати уособлення в реченні"),
            ("odróżnić opis cechy od ożywienia", "відрізнити опис ознаки від оживлення"),
        ),
        [
            concept("Przymiotnik", "Прикметник",
                    ["**zielony las, zielona łąka, zielone pole** — końcówka idzie za rodzajem rzeczownika.",
                     "Pisownia **nie** z przymiotnikiem: zwykle razem, gdy przeczenie tworzy nową cechę (niewesoły), ale sprawdź zasadę stopniowania na lekcji 18."],
                    ["**zielony las, zielona łąka** — закінчення йде за родом іменника."]),
            concept("Uosobienie", "Уособлення",
                    ["Wiatr **szepcze**. Rzeka **idzie** do morza. To nie raport meteorologa — to środek poetycki.",
                     "Uosobienie ≠ apostrofa. Apostrofa woła. Uosobienie każe rzeczy działać jak człowiek."],
                    ["Вітер **шепоче**. Річка **йде** до моря. Це поетичний засіб.",
                     "Уособлення ≠ апострофа. Апострофа кличе. Уособлення змушує річ діяти як людина."]),
        ],
        choice(16, "Które zdanie zawiera uosobienie?", "Яке речення містить уособлення?",
               [("Wiatr jest zimny.", "Вітер холодний."),
                ("Wiatr szepcze do okna.", "Вітер шепоче до вікна."),
                ("Wiatr to rzeczownik.", "Вітер — іменник.")],
               "b", "Szepcze = cecha człowieka.", "Шепоче = риса людини."),
        fill(16, "Na jakie pytanie odpowiada przymiotnik? (jaki?)",
             "На яке питання відповідає прикметник? (jaki?)",
             ["jaki?", "jaki? jaka? jakie?", "jaki", "який?"],
             "jaki? jaka? jakie?", "який? яка? яке?"),
        wrong("„Uosobienie to to samo co apostrofa: zawsze wołamy O wietrze!”",
              "«Уособлення — те саме, що апострофа: завжди кличемо O wietrze!»",
              ["Apostrofa = zwrot. Uosobienie = rzecz zachowuje się jak ktoś."],
              ["Апострофа = звертання. Уособлення = річ поводиться як хтось."]),
        oral(16, "Ułóż na głos jedno uosobienie (deszcz, noc albo drzewo).",
             "Склади вголос одне уособлення (дощ, ніч або дерево).",
             "Co robi przymiotnik w związku z rzeczownikiem?",
             "Що робить прикметник у зв’язку з іменником?",
             [("zgadza się z nim w rodzaju, liczbie i przypadku",
               "узгоджується з ним у роді, числі й відмінку"),
              ("zawsze stoi w bezokoliczniku", "завжди стоїть в інфінітиві"),
              ("zastępuje kropkę", "замінює крапку")],
             "a", "Zgoda gramatyczna.", "Граматична узгодженість."),
        [
            ("Przymiotnik mówi, jaki jest rzeczownik, i zgadza się z nim gramatycznie.",
             ["Przymiotnik", "zgadza się"],
             "Прикметник каже, який є іменник, і узгоджується з ним граматично.",
             ["Прикметник", "узгоджується"]),
            ("Uosobienie nadaje rzeczom i zjawiskom cechy człowieka.",
             ["Uosobienie"],
             "Уособлення надає речам і явищам риси людини.",
             ["Уособлення"]),
        ],
    ),
]
